### ISSUE TITLE
When will you release the code for pre-training

### ISSUE THREAD

**Issue by qwopqwop200** [YuliangXiu/ICON#1]
Hello

the paper is great and the result is impressive. May I ask when are you going to release the code for pre-training?

**Comment by YuliangXiu** [comment]
Thanks. I am still cleaning the code and tuning the model for better performance, the release won't be later than the mid of March. You could press "watch" button to receive notification for future updates (e.g., pull request, release, contributions).

**Comment by YuliangXiu** [comment]
@qwopqwop200 The inference code is released.

**Comment by hust-kevin** [comment]
@YuliangXiu thank for your job, May I ask mpe will release train code of pare and pixie?

**Comment by YuliangXiu** [comment]
[Dataset processing](https://github.com/YuliangXiu/ICON/blob/master/docs/dataset.md)
[Training](https://github.com/YuliangXiu/ICON/blob/master/docs/training.md)
