### ISSUE TITLE
Colab main cell doing nothing

### ISSUE THREAD

**Issue by smithee77** [YuliangXiu/ICON#100]
Hi, first thanks for your code
In colab version, when running the cell that starts with
# run the test on examples

the execution is very fast, no errors, but do nothing. Next cell show errors:
FileNotFoundError: [Errno 2] No such file or directory: '/content/ICON/results/icon-filter/vid/22097467bffc92d4a5c4246f7d4edb75_display.mp4'

many thanks

**Comment by YuliangXiu** [comment]
Have u already run all blocks? Just start from the `git clone` block and the following setup takes 10 min around.

Also, you can use <a href="https://huggingface.co/spaces/Yuliang/ICON"  style='padding-left: 0.5rem;'><img src='https://img.shields.io/badge/%F0%9F%A4%97%20Hugging%20Face-Spaces-orange'></a>

**Comment by smithee77** [comment]
Hi @YuliangXiu thanks for fast response.
Yes, all the blocks were run. Also tried restarting running environment, but same result, no error but "no actions" either.

Regards

**Comment by smithee77** [comment]
Hi back @YuliangXiu 
if I uncomment "clear_output()" in the cell that runs it all, I'm getting this error:

ModuleNotFoundError: No module named 'pytorch3d'
I've tried to !pip install pytorch3d in colab environment but it's not working. Also, in "requirements_colab.txt" that package is present, but somehow it's not being installed in the conda environment???

many thanks again

**Comment by YuliangXiu** [comment]
Thanks for your feedback, I just updated the requirement files, see [commit](https://github.com/YuliangXiu/ICON/commit/f0fab225af66e8fa12267e4a72cb9742feb47187)

**Comment by smithee77** [comment]
Hi @YuliangXiu ...closer but we're not still there ;)
With new changes, I'm getting this error:
ImportError: Numba needs NumPy 1.22 or less

Thanks again

**Comment by YuliangXiu** [comment]
> Hi @YuliangXiu ...closer but we're not still there ;) With new changes, I'm getting this error: ImportError: Numba needs NumPy 1.22 or less
> 
> Thanks again
```bash
!source activate icon && pip install numpy==1.22.4
```

**Comment by smithee77** [comment]
AssertionError: Path /content/ICON/lib/dataset/../../data/smpl_related/models/smpl does not exist!

(I've downloaded ALL optional models)

**Comment by YuliangXiu** [comment]
You don't need to download any optional models, I think you should run `fetch_data.sh` again.

**Comment by smithee77** [comment]
@YuliangXiu I had to manually create some folders to make it work...but running now! ;) 

%mkdir /content/ICON/data
%mkdir /content/ICON/data/smpl_related
%mkdir /content/ICON/data/smpl_related/models
%mkdir /content/ICON/data/smpl_related/models/smpl



many thanks for your support
