### ISSUE TITLE
rembg requires python=3.9 but python=3.8 in environment.yaml?

### ISSUE THREAD

**Issue by crazySyaoran** [YuliangXiu/ICON#101]
rembg says it requires python=3.9 but python=3.8 in environment.yaml.

Has anyone successfully installed the environment through the readme?

**Comment by crazySyaoran** [comment]
Well. I installed python=3.9 and another packages manually. And it finally worked.

**Comment by YuliangXiu** [comment]
I updated the requirement.txt file yesterday, you can check this [commit](https://github.com/YuliangXiu/ICON/commit/fff461b19c2bc599f923e5bf8fa6066034455440)
