### ISSUE TITLE
[Colab] Inference stops in the first image of the folder

### ISSUE THREAD

**Issue by smithee77** [YuliangXiu/ICON#102]
Using Colab, I have a folder  {image_folder} with several images.

In line:

```bash
!source activate icon && pip install numpy==1.22.4 && python -m apps.infer -cfg ./configs/{model}.yaml -loop_smpl {loop_smpl} -loop_cloth 200 -colab -gpu 0 -export_video -in_dir {image_folder}
```

Execution stops in the first image, showing this message:

```basj
[F unbatched_triangle_distance_cuda.cu:441] Check failed: error == cudaSuccess (209 vs. 0)  no kernel image is available for execution on the device
```
No more images are processed.

Regards

**Comment by YuliangXiu** [comment]
I made some changes to the requirements files (already being merged into the current repo) and tried to run all the Colab blocks, they work well. I highly recommend to re-open the Colab, and running the rest blocks without any modification,

**Comment by smithee77** [comment]
Hi @YuliangXiu just reopen Colab from your github, and run with Colab Pro +

I'm getting same error, it only works with one image from examples folder (first one - 22097467bffc92d4a5c4246f7d4edb75.png), and stops with same error as reported above ( I just commented clear_output() to see cell output )

Thanks

**Comment by YuliangXiu** [comment]
<img width="627" alt="image" src="https://user-images.githubusercontent.com/7944350/183529115-95a1711a-27ed-4f43-b7ff-707289fe1551.png">

Have you selected GPU as above? Please select GPU mode and then re-install everything. Also, if you want to test more than one image, please remove `-colab` like 

```bash
!source activate icon && pip install numpy==1.22.4 && python -m apps.infer -cfg ./configs/{model}.yaml -loop_smpl {loop_smpl} -loop_cloth 200 -gpu 0 -export_video -in_dir {image_folder}
```

**Comment by smithee77** [comment]
Hi @YuliangXiu 
Yes, always with GPU, now I'm working with Tesla V100-SXM2 Colab Pro +
I've removed "-colab" and same performance (error message and stops in first image). I guess that message error that I reported stops the execution, and I can't get no more than one image.

Any hint?
Thanks

**Comment by YuliangXiu** [comment]
We have exactly the same GPU setting

<img width="762" alt="image" src="https://user-images.githubusercontent.com/7944350/183699435-d27c2655-2370-478a-9670-b9df1859746a.png">

And I run the Colab again from scratch, and here is the log after removing `-colab`, it does work well on multiple images under the same folder

<img width="927" alt="image" src="https://user-images.githubusercontent.com/7944350/183698976-e9e224c4-e050-4e90-beaf-7cceff619c97.png">

BTW, I didn't use **Colab Pro +**, this is not necessary for ICON.

**Comment by smithee77** [comment]
ok. thanks again, quite weird. 
The only diffence is GPU model (T4 vs V100)...will try to get that GPU in a free suscription (Colab Pro + will never give me that GPU)
