### ISSUE TITLE
kaolin rembg pillow version issue

### ISSUE THREAD

**Issue by OvOtoQAQ** [YuliangXiu/ICON#103]
Thanks for releasing all the codes of this excellent work!

I have some problems when I follow your installation instrucion, your requirement file says ``` pillow==9.0.0 ``` is needed, while rembg requires ``` pillow>=9.0.1 ``` and also ``` scipy>=1.8.0 ```, but sadly the ```kaolin 0.12.0``` needs ``` scipy<=1.7.2 ```

I'm so confused which is strictly required, and one more thing is that I can't find how to install rembg==2.0.13 which you remarked bellow an issue about you envs since the official website says the oldest version is 2.0.14.

please show me more details, thanks again

**Comment by YuliangXiu** [comment]
Please refer to the latest [requirements.txt](https://github.com/YuliangXiu/ICON/blob/master/requirements.txt)
