### ISSUE TITLE
Colab: error with pytorch3d

### ISSUE THREAD

**Issue by smithee77** [YuliangXiu/ICON#105]
Hi @YuliangXiu , I'm running your Colab notebook (no changes), in this Colab environment:
GPU: Tesla T4
NVIDIA-SMI 460.32.03   
Driver Version: 460.32.03   
CUDA Version: 11.2 

In line
`!source activate icon && python -m apps.infer -cfg ./configs/{model}.yaml -loop_smpl {loop_smpl} -loop_cloth 200 -colab -gpu 0 -export_video -in_dir {image_folder}
`
I get this error:
`ImportError: /usr/local/envs/icon/lib/python3.8/site-packages/pytorch3d/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor7is_cudaEv`

It's weird because yesterday everything was running ok .

Many thanks again for your support.

**Comment by YuliangXiu** [comment]
This is a new [issue](https://github.com/facebookresearch/pytorch3d/issues/1289) for PyTorch3D.

Here is the solution for Colab:
```bash
!source activate icon
!pip wheel git+https://github.com/facebookresearch/pytorch3d.git
```

**Comment by YuliangXiu** [comment]
I updated the [requirements_colab.txt](https://github.com/YuliangXiu/ICON/commit/245f8694dc3861e757f4c2dd2ce0da8116792d5b) with pre-built wheel url, the colab should work well with it.

**Comment by smithee77** [comment]
@YuliangXiu great. After some days of experiments, I share one conclussion. Colab code right now works perfect on GPUs offered by free Colab (Tesla T4 usually), but it fails to work with Colab Pro+ better GPUs (Tesla V100, for example).

Many thanks as always

**Comment by YuliangXiu** [comment]
@smithee77 Please firstly look for solutions from existing issues and don't raise questions in the discussion panel.
