### ISSUE TITLE
Installation Error in pymeshlab: ImportError: libglib-2.0.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by MikoSamey** [YuliangXiu/ICON#106]
I used `pip install -r requirements.txt --use-deprecated=legacy-resolver` to install all the requirements in Linux.
Everything seems to install fine - however when I try to run the Demo I get the following error:
```bash
(icon) root:/# python
Python 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:18) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymeshlab
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/miniconda3/envs/icon/lib/python3.8/site-packages/pymeshlab/__init__.py", line 14, in <module>
    from .pmeshlab import *
ImportError: libglib-2.0.so.0: cannot open shared object file: No such file or directory
```

Strangely, I also installed `pymeshlab==0.2.1` in another Linux,for its GLIBC version is GLIBC_2.23.It's runnable,and it does not have this file `libglib-2.0.so.0`. 
But in this Linux, `kaolin` cannot be used, because I get the following error:
```bash
  File "/usr/local/anaconda3/envs/icon/lib/python3.8/site-packages/kaolin/ops/batch.py", line 17, in <module>
    from kaolin import _C
ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
```

So on both systems I can't run ICON. Do you have any suggestions for how I can get this running?

Thanks!

**Comment by YuliangXiu** [comment]
Never seen such errors so it seems like an uncommon issue specific to your machine, tried the solutions from Google, and please let me know if all the workaround couldn't make it work

- [libtorch](https://www.google.com/search?q=ImportError%3A+libtorch_cuda_cu.so%3A+cannot+open+shared+object+file%3A+No+such+file+or+directory&oq=ImportError%3A+libtorch_cuda_cu.so%3A+cannot+open+shared+object+file%3A+No+such+file+or+directory&aqs=chrome..69i57j69i58.347j0j7&sourceid=chrome&ie=UTF-8)
- [libglib](https://www.google.com/search?q=ImportError%3A+libglib-2.0.so.0%3A+cannot+open+shared+object+file%3A+No+such+file+or+directory&oq=ImportError%3A+libglib-2.0.so.0%3A+cannot+open+shared+object+file%3A+No+such+file+or+directory&aqs=chrome..69i57j69i61j69i58.343j0j7&sourceid=chrome&ie=UTF-8)
