### ISSUE TITLE
No such file data/smpl_related/smpl_data/smpl_faces.npy

### ISSUE THREAD

**Issue by wkailiu** [YuliangXiu/ICON#108]
https://github.com/YuliangXiu/ICON/blob/42f1f00e3b84a861295cc1118be6672ac107a039/lib/dataset/mesh_util.py#L849
https://github.com/YuliangXiu/ICON/blob/42f1f00e3b84a861295cc1118be6672ac107a039/lib/dataset/mesh_util.py#L850

this file is all not in [tree-structure-of-data-folder](https://github.com/YuliangXiu/ICON/blob/master/docs/installation.md#tree-structure-of-data-folder)

**Comment by YuliangXiu** [comment]
@wkailiu I have updated the `icon_data.zip`, which contains `smpl_faces.npy`
