### ISSUE TITLE
camera parameters

### ISSUE THREAD

**Issue by zhan-xu** [YuliangXiu/ICON#109]
Hi, thanks for the code! I am wondering if there is a way to get camera intrinsic & extrinsic matrices to project the predicted mesh onto the original images. I noticed in the code, mesh is first projected to the cropped patch and then unwrap to the original image, but I couldn't figure out how to get the proper camera parameters to achieve the correct alignment. Any help or hint would be appreciated. Thank you.

**Comment by YuliangXiu** [comment]
You can refer to [garment extraction](https://github.com/YuliangXiu/ICON/blob/master/docs/garment-extraction.md)

**Comment by gushengbo** [comment]
@zhan-xu , hello, may I ask you that how you get the camera intrinsic?
