### ISSUE TITLE
the cpu cost 

### ISSUE THREAD

**Issue by River-Zhang** [YuliangXiu/ICON#113]
Hi, I follow the instruction and run the training procedure. But I found that the cpu cost is too much. There are 8 threads and each takes over 600% cpu. However the GPU cost is just ok. I wonder why this procedure cost too much cpu.

**Comment by YuliangXiu** [comment]
> Hi, I follow the instruction and run the training procedure. But I found that the cpu cost is too much. There are 8 threads and each takes over 600% cpu. However the GPU cost is just ok. I wonder why this procedure cost too much cpu.

The high CPU computing should come from dataloader, there are lots of operations, e.g., occupancy computation, image processing, and SMPL inference are conducted inside dataloader

**Comment by River-Zhang** [comment]
It seems that in previous version the problem is caused by get_sampling_geo() function. But in the new released version the cpu cost seems acceptable.
