### ISSUE TITLE
GPU requirements to finish all ICON experiments

### ISSUE THREAD

**Issue by BigBang019** [YuliangXiu/ICON#115]
Hi, I didn't find description about your testbed setup in your original paper.

I wonder how many GPUs have you used in your experiments.

**Comment by YuliangXiu** [comment]
It's in the [installation](https://github.com/YuliangXiu/ICON/blob/master/docs/installation.md#environment), all the training and testings could be conducted with single GPU with memory > 12GB.

**Comment by BigBang019** [comment]
Hi, I still have some questions. How much GPU cost is required to train a SMPL-like model from scratch?
