### ISSUE TITLE
SMPL params for PAMIR on CAPE Test?

### ISSUE THREAD

**Issue by hanhuili** [YuliangXiu/ICON#118]
Thanks for the great work. Can you provide the pkl files for the estimated SMPL and SMPLX models on the CAPE test set? Currently, the provided zip file only contains SMPL obj files.

**Comment by YuliangXiu** [comment]
Hi @hanhuili 

I have updated the `icon_test.zip`, `fits` contains the SMPL parameters files (.npz). Unfortunately, CAPE does not have SMPL-X fits.

**Comment by hcp6897** [comment]
I executed this script fetch_cape.sh to download the ICON_test.zip. Unfortunately, this zip file have been destroyed and do not unzip.

**Comment by YuliangXiu** [comment]
> I executed this script fetch_cape.sh to download the ICON_test.zip. Unfortunately, this zip file have been destroyed and do not unzip.

I re-downloaded this file, and `unzip` works well for me. Maybe you could also download it from [web browser](https://cape.is.tue.mpg.de/download.php).
