### ISSUE TITLE
np.load can not load .obj file

### ISSUE THREAD

**Issue by tdqcb** [YuliangXiu/ICON#121]
Hi, I am very interested in your work and want to try. But I got an  error when I run python -m lib.dataloader_demo -v -c ./configs/train/pamir.yaml

```bash

(icon) gdl@gdl:~/Desktop/wangting/ICON-master$ python -m lib.dataloader_demo -v -c ./configs/train/pamir.yaml
load from ./data/thuman2/test.txt
Number of subjects :4
smpl_path ./data/thuman2/fits/0007/smpl_param.pkl
smplx_path ./data/thuman2/fits/0007/smplx_param.pkl
Traceback (most recent call last):
  File "/home/gdl/anaconda3/envs/icon/lib/python3.8/site-packages/numpy/lib/npyio.py", line 438, in load
    return pickle.load(fid, **pickle_kwargs)
_pickle.UnpicklingError: invalid load key, '#'.

```

The above exception was the direct cause of the following exception:

```bash

Traceback (most recent call last):
  File "/home/gdl/anaconda3/envs/icon/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/gdl/anaconda3/envs/icon/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/gdl/Desktop/wangting/ICON-master/lib/dataloader_demo.py", line 42, in <module>
    data_dict = dataset[1]
  File "/home/gdl/Desktop/wangting/ICON-master/lib/dataset/PIFuDataset.py", line 283, in __getitem__
    data_dict.update(self.load_smpl_voxel(data_dict))
  File "/home/gdl/Desktop/wangting/ICON-master/lib/dataset/PIFuDataset.py", line 552, in load_smpl_voxel
    smpl_verts, smpl_faces, pad_v_num, pad_f_num = self.compute_voxel_verts(
  File "/home/gdl/Desktop/wangting/ICON-master/lib/dataset/PIFuDataset.py", line 415, in compute_voxel_verts
    smpl_param = np.load(data_dict['smpl_path'], allow_pickle=True)
  File "/home/gdl/anaconda3/envs/icon/lib/python3.8/site-packages/numpy/lib/npyio.py", line 440, in load
    raise pickle.UnpicklingError(
_pickle.UnpicklingError: Failed to interpret file './data/thuman2/smpl/0007.obj' as a pickle
```

my numpy version is 1.22.4 ,at frst ,I try to solve the problem by https://github.com/YuliangXiu/ICON/issues/98, but it don't work,Can you give me some advice?

**Comment by YuliangXiu** [comment]
Just updated the [code](https://github.com/YuliangXiu/ICON/commit/3aceec861fb1c1c14071265fd51914513cf743a7), `smpl(x)_path` is the path for mesh obj, `smpl(x)_param` is the path for pkl parameters.

**Comment by tdqcb** [comment]
Dear Dr.&nbsp;Yuliang Xiu:
&nbsp; &nbsp; &nbsp;First,thank you very much for your help.I tryed the method you gave me, but there are new problems:

after I changed the attribute of 'full_pode' to 'body_pose',there are now new problem.&nbsp;

Can you give me some help?








一陆向北
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YuliangXiu/ICON"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月6日(星期四) 凌晨4:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YuliangXiu/ICON] np.load can not load .obj file (Issue #121)





 
Just updated the code, smpl(x)_path is the path for mesh obj, smpl(x)_param is the path for pkl parameters.

**Comment by tdqcb** [comment]
I changed code according the method that you provided,but new problem occured .the file 'smpl_param.pkl' have no key 'full_pose',then I change 'full_pose' to 'body pose',but the shape is error,can you give me some help?

(icon) gdl@gdl:~/Desktop/wangting/ICON-master$ python -m lib.dataloader_demo -v -c ./configs/train/pamir.yaml
/home/gdl/anaconda3/envs/icon/lib/python3.8/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
load from ./data/thuman2/test.txt
Number of subjects :9
{'global_orient': array([[-0.2577994 ,  1.3495909 , -0.19527189]]), '**body_pose':** array([[[ 1.46435215e-01, -4.48708190e-03,  1.89517323e-01],
        [-6.21869468e-01, -1.05050030e-01, -4.34111741e-02],
        [ 2.63547037e-01, -1.52487207e-01,  1.56659802e-01],
        [-1.71819317e-01, -1.64465648e-01,  4.40432130e-02],
        [ 1.67020235e+00, -8.67289795e-02,  3.06503940e-01],
        [-2.72811443e-01, -4.31228779e-04,  7.82719621e-02],
        [ 2.58956031e-01,  1.72923610e-01,  3.58472838e-03],
        [-4.91317612e-01, -2.39451260e-01,  3.36559021e-01],
        [ 2.61760222e-01, -1.14892970e-02,  7.03994970e-02],
        [-6.82931698e-01,  5.37374971e-01,  2.42266410e-02],
        [ 2.00156330e-01,  2.64839684e-01, -2.95057164e-01],
        [-3.08961783e-02, -1.73576950e-01,  3.68249540e-01],
        [-2.71585852e-01, -7.26955701e-03,  3.52532446e-01],
        [-3.62987465e-02, -1.10712132e-02,  1.25950698e-01],
        [ 3.27744427e-02, -3.51352246e-01, -1.74528572e-01],
        [ 3.99068150e-03, -2.15150290e-01,  1.16452384e-01],
        [ 1.79884334e-01,  1.57995513e-01,  1.00093164e+00],
        [-2.02023344e-01, -1.81487666e+00,  8.84970364e-01],
        [ 5.20967808e-02,  2.57767114e-01, -3.28617492e-01],
        [ 3.67027066e-01, -7.73467833e-02,  4.61679879e-01],
        [ 7.49815512e-01, -3.20876300e-01, -4.45156718e-01],
        [-1.22876506e+00, -4.92107497e-01, -1.93734096e+00],
        [-1.22736314e+00,  4.99016179e-01,  1.72180648e+00]]]), 'betas': array([[ 0.762956  , -1.0266448 ,  0.4842316 ,  0.39761072, -0.81847614,
         0.22849987,  0.8460495 ,  0.46218655,  1.042012  ,  1.5854723 ]],
      dtype=float32), 'transl': TrackedArray([[ 0.00035985,  0.05110257, -0.01051249]]), 'scale': array([0.3176894])}
Traceback (most recent call last):
  File "/home/gdl/anaconda3/envs/icon/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/gdl/anaconda3/envs/icon/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/gdl/Desktop/wangting/ICON-master/lib/dataloader_demo.py", line 41, in <module>
    data_dict = dataset[1]
  File "/home/gdl/Desktop/wangting/ICON-master/lib/dataset/PIFuDataset.py", line 285, in __getitem__
    data_dict.update(self.load_smpl_voxel(data_dict))
  File "/home/gdl/Desktop/wangting/ICON-master/lib/dataset/PIFuDataset.py", line 553, in load_smpl_voxel
    smpl_verts, smpl_faces, pad_v_num, pad_f_num = self.compute_voxel_verts(
  File "/home/gdl/Desktop/wangting/ICON-master/lib/dataset/PIFuDataset.py", line 421, in compute_voxel_verts
    torch.as_tensor(smpl_param['full_pose'][0])).numpy()
KeyError: 'full_pose'

change 'full_pose' to 'body pose',the new problem:
File "/home/gdl/Desktop/wangting/ICON-master/lib/pare/pare/utils/geometry.py", line 242, in rotation_matrix_to_quaternion
    raise ValueError(
ValueError: Input size must be a N x 3 x 4  tensor. Got torch.Size([23, 3])
