### ISSUE TITLE
the result of icon-keypoint is bad

### ISSUE THREAD

**Issue by ZhangLei999** [YuliangXiu/ICON#124]
After run the command:
python -m apps.infer -cfg ./configs/icon-keypoint.yaml -gpu 0 -in_dir ./examples -out_dir ./results -export_video -loop_smpl 100 -loop_cloth 200 -hps_type pymaf

recon.obj doesn't look good!

**Comment by YuliangXiu** [comment]
Yes, in terms of pose robustness, ICON w/ SMPL-SDF performs better than ICON w/ keypoints. For challenging poses under `./examples`, the reconstructions of ICON-Keypoint are always with floating artifacts or broken limbs. Also, the provided `icon-keypoint.ckpt` is only trained on 500 THuman2.0 scans.

**Comment by Gary-Qinghua** [comment]
Thanks for your quick reply.
![20221013101819](https://user-images.githubusercontent.com/73276075/195483937-e987b712-0d37-4128-84f1-b22c22ae2957.png)
![20221013101845](https://user-images.githubusercontent.com/73276075/195483946-e0137bd4-4792-4861-8a6d-542b0d2c8200.png)

**Comment by dyy0205** [comment]
hi, sorry to bother you, but where can i download the icon-keypoint.ckpt @YuliangXiu
