### ISSUE TITLE
Scripts transform CAPE dataset to ICON format dataset (like icon_test.zip)

### ISSUE THREAD

**Issue by ms-xie** [YuliangXiu/ICON#129]
Hi, 
Thanks for the great work and codes, I am currently engaged in research in this field.

Since testing on CAPE is available, could you please release the scripts that transform CAPE dataset to ICON format dataset (like icon_test.zip)? Or a new branch under CAPE with ICON format?
Is Raw Scans in CAPE is needed or not? 
I will appreciate any of your help or advice! Thanks

**Comment by YuliangXiu** [comment]
Yes, raw textured scans are needed for training. `icon_test.zip` is a subset of CAPE, w/ textured scans. But unfortunately, not all the textured scans of CAPE are publicly available.

**Comment by ms-xie** [comment]
Thanks for reply! 
I am wondering if the CAPE dataset includes 3D skeleton?

**Comment by YuliangXiu** [comment]
It contains corresponding SMPL fits, so YES.
