### ISSUE TITLE
Meet ERROR when running vis_batch.sh

### ISSUE THREAD

**Issue by CapenZen** [YuliangXiu/ICON#133]
(icon) capen@lucky:~/ICON$ bash scripts/vis_batch.sh debug all
thuman2 START----------
Debug visibility
Visibility thuman2 0499
/home/capen/.conda/envs/icon/lib/python3.8/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
Traceback (most recent call last):
  File "scripts/vis_single.py", line 50, in <module>
    calib_verts = projection(smpl_verts, calib, format='tensor')
TypeError: projection() got an unexpected keyword argument 'format'
thuman2 END----------

**Comment by YuliangXiu** [comment]
It's correct.
