### ISSUE TITLE
FileNotFoundError : eyeball_fid.npy, fill_mouth_fid.npy

### ISSUE THREAD

**Issue by Leesangoh** [YuliangXiu/ICON#134]
<img width="783" alt="image" src="https://user-images.githubusercontent.com/68114701/197000725-e22ce4df-7eb1-47ba-b829-e6ee0e0fac31.png">

Hi, I'm really interested in your research and trying to run the code (I run python -m apps.train -cfg ./configs/train/icon-filter.yaml)

However, I faced with the error : FileNotFoundError: [Errno 2] No such file or directory: '/local_data_2/ug_psh/ICON/lib/dataset/../../data/smpl_related/smpl_data/eyeball_fid.npy' 

I tried to find them on internet for several hours, but couldn't find them. (even cannot find in the smplx homepage)

Where can I get them?

**Comment by YuliangXiu** [comment]
These files were updated in `icon_data.zip` a few weeks ago, you could download it again.

**Comment by yangqinhui0423** [comment]
> These files were updated in `icon_data.zip` a few weeks ago, you could download it again.

Hello! I want to know where I can find the file **icon_data.zip.**
