### ISSUE TITLE
Is it ok to change NUM_THREADS when running render_batch.sh and vis_batch.sh?

### ISSUE THREAD

**Issue by Zhangjzh** [YuliangXiu/ICON#137]
I was trying to run render_batch.sh and vis_batch.sh. But I got EGL_BAD_ALLOC error and out of memory error.
I changed the NUM_THREADS to 4 and 2 respectively, and it worked.

But I am not sure whether it is ok to do so. Will this affect the training stage or the test result?

**Comment by YuliangXiu** [comment]
Don't worry. **NUM_THREAD** only affect the rendering speed.
