### ISSUE TITLE
Can I change the smpl model gender

### ISSUE THREAD

**Issue by CongSuxu** [YuliangXiu/ICON#138]
I found out that the gender of the model is neutral and fixed in the code, can i change it to female or male. I changed the gender in code but get bad results. Then I add the --loop_smpl from 1 to 200, but get "CUDA error: initialization error when calling `cusparseCreate(handle)`"

**Comment by YuliangXiu** [comment]
This is related to off-the-shell HPS approach (human pose & shape estimation), you could switch to `PIXIE`, 'PyMAF' only supports neutral shape.

**Comment by CongSuxu** [comment]
Thank you for your reply! Should I set the hps_type to `PIXIE`, then just change all the "neutral" in code to either "female" or "male"?

**Comment by YuliangXiu** [comment]
Don't need to change any other codes

> "PIXIE estimates bodies with a gender-appropriate shape but does so in a gender neutral shape space to accommodate non-binary shapes"

Please check [PIXIE](https://github.com/YadiraF/PIXIE) for more details.
