### ISSUE TITLE
pare-github-data.zip download failed

### ISSUE THREAD

**Issue by lyk412** [YuliangXiu/ICON#139]
Hi! Thanks for your open source work. I encountered a problem when downloading pare-github-data.zip. I failed by running script `wget https://www.dropbox.com/s/aeulffqzb3zmh8x/pare-github-data.zip`, because the connection timed out. Then I tried to download from Dropbox manually, but when the progress bar shows "1.2G/1.2G" I was informed that "Unable to download, network problem" . I have tried many times, but got the same result. Could you upload this dataset to the cloud  that can be accessed in China, such as Baidu Cloud. Thank you very much!
![1666847774774](https://user-images.githubusercontent.com/65889678/198197961-c8de74c7-9bf8-4370-afb2-8d9a0d257350.jpg)

**Comment by YuliangXiu** [comment]
I uploaded this file under ICON's ftp `https://download.is.tue.mpg.de/download.php?domain=cape&resume=1&sfile=pare-github-data.zip`

Please refer to [fetch_cape.sh](https://github.com/YuliangXiu/ICON/blob/master/fetch_cape.sh) to download it
