### ISSUE TITLE
How to generate test.txt?

### ISSUE THREAD

**Issue by Zhangjzh** [YuliangXiu/ICON#140]
I was trying to run following scripts:
python -m lib.dataloader_demo -v -c ./configs/train/icon-filter.yaml
and I got following error:
FileNotFoundError: ./data/thuman2/test.txt not found
However, I didn't find instructions on how to generate test.txt. Could you please tell me which subject names test.txt should contain?
Thank you very much!

**Comment by YuliangXiu** [comment]
[Here](https://github.com/YuliangXiu/ICON/blob/master/lib/dataset/PIFuDataset.py#L166) is the code to split `all.txt` to `train/val/test.txt`

Or you can also move [L129](https://github.com/YuliangXiu/ICON/blob/master/lib/dataset/PIFuDataset.py#L129) before [L104](https://github.com/YuliangXiu/ICON/blob/master/lib/dataset/PIFuDataset.py#L104)

**Comment by TShoreWind** [comment]
@YuliangXiu Dear author, I still don't know where to start for generating test.txt.

**Comment by TShoreWind** [comment]
@Zhangjzh How did you solve this problem
