### ISSUE TITLE
Question for Reproducing Result

### ISSUE THREAD

**Issue by EadCat** [YuliangXiu/ICON#141]
Hi, I reproduced ICON and trained with THuman2.0.

As a result of the my training, only this model produces a lot of noise and isolated mesh.

Would you give me an advice?

I used [-1, 1] SMPL vertices, query points, and 15.0 SDF clipping.

I believe that ICON has great potential and generalization performance.

But I don't know what is the problem.

The results below are about unseen data, and I used pre-trained GCMR just like PaMIR for SMPL prediction.

![snapshot00](https://user-images.githubusercontent.com/59416168/200036692-1d243f22-77d0-4fad-803c-54796b801494.png)
![snapshot01](https://user-images.githubusercontent.com/59416168/200036695-5e47ca40-ab0b-4ae7-9324-ac9aa78c2543.png)
![snapshot02](https://user-images.githubusercontent.com/59416168/200036698-414ca927-b04f-40fd-a70c-ce82fb630662.png)
![snapshot03](https://user-images.githubusercontent.com/59416168/200036700-36915c77-3890-420a-81f3-c33c68597de2.png)
![snapshot04](https://user-images.githubusercontent.com/59416168/200036703-62cedb88-d1bf-430d-9c0c-4902ef44d8e3.png)
![snapshot05](https://user-images.githubusercontent.com/59416168/200036706-186b5cec-5b83-44e2-8e1d-54a9ef17e430.png)

Thank you.

**Comment by EadCat** [comment]
<img width="801" alt="20221105023427" src="https://user-images.githubusercontent.com/59416168/200039828-8b71c9ed-2131-4bb7-92de-5e9f071ef433.png">

This is my query code of ICON.

**Comment by YuliangXiu** [comment]
`smpl_cmap` and `smpl_norm` are not necessary for the reconstruction, you could remove them one by one, retrain and check the results. Also, the `SDF--> TSDF` operation also could be removed.

**Comment by EadCat** [comment]
Are ```smpl_vis``` and ```feat_select``` necessary?
They are seem to optional in your code.

**Comment by YuliangXiu** [comment]
I am afraid not.

Given only the `smpl_sdf`, it's almost impossible for the network to figure out which normal should be used. Maybe `smpl_norm` should be included in such case.

**Comment by EadCat** [comment]
<img width="641" alt="snapshot00" src="https://user-images.githubusercontent.com/59416168/200279487-f8ab7f6a-eccc-4e70-98fa-e69c0efd433f.png">
<img width="641" alt="snapshot01" src="https://user-images.githubusercontent.com/59416168/200279497-04c5ef4b-d3df-4418-8b3a-353a9020b03a.png">

I only removed ```TSDF``` operation and got better results.

Many thanks!

**Comment by YuliangXiu** [comment]
@EadCat These noisy artifacts could be reduced with current normal refinement module in ICON, set `-loop_cloth 50`.

**Comment by EadCat** [comment]
Sure. I will implement pre-/post-optimizations.
Thank you for the helps.
