### ISSUE TITLE
how to get minimal-body for the SCANimate

### ISSUE THREAD

**Issue by Gary-Qinghua** [YuliangXiu/ICON#142]
Hi, I want to use SCANimate for Animation. How to generate the minimal-body of my own dataset?
The author suggested that use Smplx-fitting, but it can't generate very well because of the lack of detail in face.
Can you give some advice? Thanks.

**Comment by YuliangXiu** [comment]
SCANimate does not work well on face, hands or feet, they cut these parts during canonicalizaton.

**Comment by ZhangLei999** [comment]
Thanks for your quick reply.
So I use  Smpl-fitting to generate the minimal-body of my own dataset, its face is not delicate and does not affect the final result?

**Comment by Gary-Qinghua** [comment]
Yes, you are right!
I'll fill in the results later

**Comment by Leesangoh** [comment]
> Thanks for your quick reply.
> So I use Smpl-fitting to generate the minimal-body of my own dataset, its face is not delicate and does not affect the final result?

If you don't mind, can you share the code for generating minimal-body ? I'm trying to make it, but it is quite hard.
