### ISSUE TITLE
Question for SDF training

### ISSUE THREAD

**Issue by tpzou** [YuliangXiu/ICON#143]
Congrats on this great work, and thanks a lot for open-sourcing this project!

I notice that the final prediction in the code is occupancy. But there are still traces of the predicted SDF in the code. I also read through some of the previous issues of SDF. It seems that the former is used due to the comparable performance of the two. 

I wonder to know how to train the SDF head. I tried to build a simply demo on it (Standard SMPL). Referring to the existing work, I choose normal supervision and SDF supervision for points on the surface, and eikonal loss for non-surface points. The results look normal.
![image](https://user-images.githubusercontent.com/54886980/200826136-075b3f27-b820-4480-a99b-23a4ef157b3f.png)

However when I try to add SDF loss on the non-surface points. The result produces a lot of noise. 

![image](https://user-images.githubusercontent.com/54886980/200826301-1efa8461-c841-40f9-9998-904dcde88a2e.png)

I also tried using DeepSDF's clamp loss, and the same problem occurs. Can you give me some advice? Or can you tell me how to use SDF predictions properly based on your code?

**Comment by YuliangXiu** [comment]
1. Check the SDF value of non-surface points
2. If you use positional encoding, remove it and see
