### ISSUE TITLE
Thuman2.0 preprocessed dataset 

### ISSUE THREAD

**Issue by Yuhuoo** [YuliangXiu/ICON#144]
Can anyone share the preprocessed Thuman2.0 dataset?

**Comment by glorioushonor** [comment]
Hi. I'm sorry to bother you. I successfully reproduced ICON, but I found some problems with my quantitative data, which I now suspect is the problem with the synthesized data. Could you please share the composite data of THuman2.0?

**Comment by lywudi** [comment]
> Hi. I'm sorry to bother you. I successfully reproduced ICON, but I found some problems with my quantitative data, which I now suspect is the problem with the synthesized data. Could you please share the composite data of THuman2.0?嗨 我很抱歉打扰你。 我成功地再现图标，但是我发现了一些问题与我的定量数据，这些数据现在我怀疑是问题的合成数据。 能不能请你分享的综合数据的THuman2.0?
Can you share the preprocessed Thuman2.0 dataset?Thank you very much.
