### ISSUE TITLE
Environment configuration issues

### ISSUE THREAD

**Issue by kobeming** [YuliangXiu/ICON#146]
Hello,what should I do if I encounter this problem when configuring the environment?Can you give me some advice？
![123](https://user-images.githubusercontent.com/113109194/201575290-2e1fbf73-156f-40b5-a2f1-ef5d0dadea40.jpg)

**Comment by R33333** [comment]
Hello, have you solved this problem？I have the same problem as you.

**Comment by R33333** [comment]
I tried many methods. Finally, I found that the problem was the gcc version. My previous version gcc==11.3.  After I changed it to 7.5, the installation was successful
