### ISSUE TITLE
Error when pip install neural_voxelization_layer

### ISSUE THREAD

**Issue by lyk412** [YuliangXiu/ICON#149]
Hi, I encounter an error when I run `pip install  git+https://github.com/YuliangXiu/neural_voxelization_layer.git`.
 In short, the error is
` raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
      RuntimeError:
      The detected CUDA version (10.1) mismatches the version that was used to compile
      PyTorch (11.3). Please make sure to use the same CUDA versions`.

I guess installing CUDA 11 is the fastest way to solve the problem. But I'm afraid it will disrupt others' environment because I share the same server with them. I wonder if you can give me some advice to solve it. Thank you so much!

I check the environment and here is the result:
`nvcc -V` 
> nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243

`nvidia-smi`
>| NVIDIA-SMI 510.85.02    Driver Version: 510.85.02    CUDA Version: 11.6     |

my cudatoolkit version is **11.3.1**

`conda list torch`

> Name                    Version                   Build  Channel
pytorch                   1.11.0          py3.8_cuda11.3_cudnn8.2.0_0    pytorch
pytorch-lightning         1.2.5                    pypi_0    pypi
pytorch-mutex             1.0                        cuda    pytorch
pytorch3d                 0.7.1           py38_cu113_pyt1110    pytorch3d-nightly
torchaudio                0.11.0               py38_cu113    pytorch
torchmetrics              0.10.2                   pypi_0    pypi
torchvision               0.12.0               py38_cu113    pytorch

**Comment by lyk412** [comment]
I choose to use another server.

**Comment by YuliangXiu** [comment]
https://github.com/YuliangXiu/neural_voxelization_layer/issues/2
