### ISSUE TITLE
collab demo error :

### ISSUE THREAD

**Issue by mytrue001** [YuliangXiu/ICON#15]
FileNotFoundError: [Errno 2] No such file or directory: '/content/ICON/apps/../lib/pymaf/core/../../../data/pymaf_data/pretrained_model/PyMAF_model_checkpoint.pt'

**Comment by YuliangXiu** [comment]
Try to upgrade the gdown, please refer to [fetch_hps.sh](https://github.com/YuliangXiu/ICON/blob/master/fetch_hps.sh#L18).

**Comment by YuliangXiu** [comment]
Please `git pull` the latest codes, I made some changes so that the `gdown` could run successfully.
