### ISSUE TITLE
Checkpoints resume

### ISSUE THREAD

**Issue by Yuhuoo** [YuliangXiu/ICON#151]
Why just load the MLP weights when resume the checkpoints for retraining?

![image](https://user-images.githubusercontent.com/91204817/203221164-e80706bb-0379-4262-848b-501a3839b280.png)

**Comment by YuliangXiu** [comment]
This MLP is not named perfectly, it contains both MLP and image filter if any.

Normal network weights come from `normal.ckpt`

**Comment by z-z-zhao** [comment]
![image](https://github.com/YuliangXiu/ICON/assets/57577944/70c7959b-307c-47b6-a728-7d64bdbfa9ee)
我发现代码在构建网络时，MLP和filter是分开构建的，所以MLP并不是filter请问是这样麻？如图所示

**Comment by z-z-zhao** [comment]
I found that when the code builds the network, the MLP and the filter are built separately, so the MLP is not the filter please is this the case? As shown in the picture

**Comment by z-z-zhao** [comment]
> This MLP is not named perfectly, it contains both MLP and image filter if any.
> 
> Normal network weights come from `normal.ckpt`

I found that when the code builds the network, the MLP and the filter are built separately, so the MLP is not the filter please is this the case? As shown in the picture
https://user-images.githubusercontent.com/57577944/237590703-70c7959b-307c-47b6-a728-7d64bdbfa9ee.png
