### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by R33333** [YuliangXiu/ICON#155]
When I run: bash scripts/vis_batch.sh gen all
thuman2 START----------
processing all the subjects
Traceback (most recent call last):
  File "scripts/vis_single.py", line 53, in <module>
    smpl_vis = get_visibility(xy, z, smpl_faces)
  File "/home/nwu/workspace/ICON-master/./lib/dataset/mesh_util.py", line 353, in get_visibility
    pix_to_face, zbuf, bary_coords, dists = rasterize_meshes(
  File "/home/nwu/anaconda3/envs/icon/lib/python3.8/site-packages/pytorch3d/renderer/mesh/rasterize_meshes.py", line 224, in rasterize_meshes
    pix_to_face, zbuf, barycentric_coords, dists = _RasterizeFaceVerts.apply(
  File "/home/nwu/anaconda3/envs/icon/lib/python3.8/site-packages/pytorch3d/renderer/mesh/rasterize_meshes.py", line 298, in forward
    pix_to_face, zbuf, barycentric_coords, dists = _C.rasterize_meshes(
RuntimeError: CUDA error: no kernel image is available for execution on the device

My nvcc -V==11.0, torch==1.8.2, nvidia-smi cuda version==11.7, and i use nvidia rtx a6000. It's said on the Internet that cuda's computing power does not match the graphics card. My card's computing power is 8.6, and I export TORCH_CUDA_ARCH_LIST="8.0", But the problem still exists. So I am very confused.

**Comment by R33333** [comment]
Can I use cuda 11.1？

**Comment by YuliangXiu** [comment]
> Can I use cuda 11.1？

It should work. This error comes from PyTorch3D, you can follow [INSTALL.md](https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md) to install it.

**Comment by R33333** [comment]
> > Can I use cuda 11.1？
> 
> It should work. This error comes from PyTorch3D, you can follow [INSTALL.md](https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md) to install it.

Thanks，after reinstall pytorch3d, it work.
