### ISSUE TITLE
How to resume training in pytorch lighting?

### ISSUE THREAD

**Issue by lyk412** [YuliangXiu/ICON#157]
Hi! In `apps/train-normal.py`, I see the code for resuming.  I want to resume training from a checkpoint of a particular epoch(for example, n), and the start epoch=n+1. Should I set flag `resume=True` in config file and set `save_weights_only=False` in ModelCheckpoint? Besides, I find the `resume_path` in the `normal.yaml` is `./data/ckpt/normal.ckpt`, which can't be found in the `./data/ckpt/normal/` when training.  Look forward to your suggestions!

<img width="464" alt="code" src="https://user-images.githubusercontent.com/65889678/204144470-63dc7e69-6098-475e-8317-2def94c05ca9.png">

**Comment by YuliangXiu** [comment]
Current version does not support `resume mode`, even though I keep this entry in the config file.

You could check [PyTorch-Lightning document](https://pytorch-lightning.readthedocs.io/en/stable/common/checkpointing_basic.html#resume-training-state) for more instructions.

**Comment by lyk412** [comment]
Thanks！
