### ISSUE TITLE
Missing './data/thuman2/fits/0001/smplx_param.pkl'

### ISSUE THREAD

**Issue by Yuhuoo** [YuliangXiu/ICON#158]
How can I find the THuman2.0 dataset smplx fits param?
I used the download commands as follows:

wget https://download.is.tue.mpg.de/icon/SMPL+X.zip --no-check-certificate -O ./data/thuman2/SMPL+X.zip
unzip ./data/thuman2/SMPL+X.zip -d ./data/thuman2/
rm ./data/thuman2/SMPL+X.zip

The data I have got like the picture shows as follows, and there wasn't "fits" directory.  But I have find some code about "./data/fits/xxx/smplx_param.pkl" in render_single.py, that's so strang for me.
![image](https://user-images.githubusercontent.com/91204817/204426410-112edcd7-25ab-4164-be29-88c8d32a06f2.png)
![image](https://user-images.githubusercontent.com/91204817/204427086-1bdee1bb-7773-4d72-a092-823e8b738c87.png)

**Comment by yang499** [comment]
Did you solve it? I had the same problem

**Comment by YuliangXiu** [comment]
Sorry for the confusion, I renamed some folders and files for cleanness, smpl and smpl-x files are put into `/smpl` and `/smplx` separately.

You can check [PIFuDataset.py#L219](https://github.com/YuliangXiu/ICON/blob/master/lib/dataset/PIFuDataset.py#L219) as reference.
