### ISSUE TITLE
How to select the model for testing?

### ISSUE THREAD

**Issue by Zhangjzh** [YuliangXiu/ICON#159]
After training, I got several models under folder normal and icon-filter. However, I don't know how to select the model for testing. I tested some models and the results are poor. Could you please tell me how to select the model for testing? Thanks very much!
![QQ图片20221202174021](https://user-images.githubusercontent.com/49779683/205264509-877f8f63-f393-44dc-915d-9831bd9121fc.png)
![QQ图片20221202174045](https://user-images.githubusercontent.com/49779683/205264515-cab4e5b9-79ac-4f36-8f4a-fbb756cee4ff.png)
![QQ图片20221202174330](https://user-images.githubusercontent.com/49779683/205264536-94733c97-05ea-4feb-b261-e3c8843ddb07.png)

**Comment by Zhangjzh** [comment]
I kinda have an idea. If I start a training process, there will be a version added at the end of the ckpt. I don't know why there are so many versions. I will do the training from the start again.

**Comment by Zhangjzh** [comment]
In my understanding, there will only be one saved ckpt in one training process. The newly saved best ckpt will cover the previously saved ckpt. Am I correct?

**Comment by YuliangXiu** [comment]
Yes, it should only save the top1 checkpoint, please check [train.py](https://github.com/YuliangXiu/ICON/blob/master/apps/train.py#L44) and [ModelCheckpoint](https://pytorch-lightning.readthedocs.io/en/stable/api/pytorch_lightning.callbacks.ModelCheckpoint.html) for more details.

**Comment by Zhangjzh** [comment]
> Yes, it should only save the top1 checkpoint, please check [train.py](https://github.com/YuliangXiu/ICON/blob/master/apps/train.py#L44) and [ModelCheckpoint](https://pytorch-lightning.readthedocs.io/en/stable/api/pytorch_lightning.callbacks.ModelCheckpoint.html) for more details.

Thank you very much!

**Comment by Zhangjzh** [comment]
I deleted all the ckpt and do the training from the start again. As can be seen from the picture, there are 3 versions ckpt of the same epoch. I think there should only be one ckpt saved. Do you have any idea why this kept happening?
![Uploading II)5}5338{S$3J{A0HZSD29.png…]()

**Comment by Zhangjzh** [comment]
Is it ok to the train icon-filter mlp and icon-nofilter simultaneously?
