### ISSUE TITLE
error in the colab

### ISSUE THREAD

**Issue by crumbface909** [YuliangXiu/ICON#16]
i get this error

AssertionError: Path /content/ICON/apps/../lib/pymaf/core/../../../data/pymaf_data/../smpl_related/models/smpl does not exist!

**Comment by YuliangXiu** [comment]
These files will be downloaded after running `bash fetch_data,sh`. Also, finish the [registration](https://github.com/YuliangXiu/ICON/blob/master/docs/Installation.md#register-at-icons-website) before running this script.
