### ISSUE TITLE
Question of  cloth refinement

### ISSUE THREAD

**Issue by Yuhuoo** [YuliangXiu/ICON#162]
Hi, I'm confused about local_affine_model in the cloth refinement. I find that you use the LocalAffine() converting the verts of the refinemesh to the affined verts. The step seems to train a Affinemodel. I know that we need get the loss between P_normal from the mesh and normal of the image to optimizer the verts, but I don't understand why we need introduct the Affinemodel. The procedure of localAffine is meaning getting the Affine Matrix under the Camera coordinate system? I confused about these.

**Comment by YuliangXiu** [comment]
This is not a learned model, but a differential optimizer for mesh registration. Please refer to the following paper for more information.

_Li, Hao, Robert W. Sumner, and Mark Pauly. "Global correspondence optimization for non‐rigid registration of depth scans." Computer graphics forum. Vol. 27. No. 5. Oxford, UK: Blackwell Publishing Ltd, 2008._
