### ISSUE TITLE
Is there a bug for sampling

### ISSUE THREAD

**Issue by Yuhuoo** [YuliangXiu/ICON#163]
I found that some points sampled were outside from [-1, 1] of xy plane, Is this a bug of sampling?
![1](https://user-images.githubusercontent.com/91204817/208449744-85fb7288-4015-4083-8721-aa432136e28b.png)

![2](https://user-images.githubusercontent.com/91204817/208449797-017deedd-8628-40c3-b6fc-56dfb4cff93d.png)

**Comment by YuliangXiu** [comment]
These outlier points will be filtered out during inference, please check [HGPIFuNet.py](https://github.com/YuliangXiu/ICON/blob/master/lib/net/HGPIFuNet.py#L292).
