### ISSUE TITLE
Dataset generation error. bash scripts Generate Mode

### ISSUE THREAD

**Issue by softmurata** [YuliangXiu/ICON#165]
Hi, I want to train ICON, but in case of generating dataset, I encountered following error

command
```
cd ICON
conda activate icon
bash scripts/render_batch.sh gen all
```

error:
```
Traceback (most recent call last):
  File "scripts/render_single.py", line 1, in <module>
    import lib.renderer.opengl_util as opengl_util
ModuleNotFoundError: No module named 'lib'
```

This error may be mean we cannot import ```lib``` directory from ICON repository...
What should I do?

**Comment by YuliangXiu** [comment]
Same issue #128 , but it was closed by the creator.

Maybe you should add the the `ICON/lib` into `sys.path` as follows:

```python
import os, sys
sys.path.append(os.path.join(os.path.dirname(__file__), "lib"))
```

Or you could change [render_single.sh#19](https://github.com/YuliangXiu/ICON/blob/master/scripts/render_single.sh#L9)

```python
PYTHON_SCRIPT="scripts/render_single.py"
-->
PYTHON_SCRIPT="scripts/render_single.py"
```

**Comment by softmurata** [comment]
Thanks!! I solved my problem.

**Comment by YuliangXiu** [comment]
@softmurata 

I have updated the scripts for training data generation [dataset.md](https://github.com/YuliangXiu/ICON/blob/master/docs/dataset.md), more easy-to-use.

**Comment by yangqinhui0423** [comment]
> Thanks!! I solved my problem.

Hello, I wonder if you met the same **"ModuleNotFoundError"** when running the second instruction "**bash scripts/vis_batch.sh debug all"**.
I followed the author's advice above and solved the error for "bash scripts/render_batch.sh debug all", but when I run **"bash scripts/vis_batch.sh debug all"**, I get error as follows:
![image](https://github.com/YuliangXiu/ICON/assets/112925344/7bb82ef8-ed54-49da-8bc7-e416cd6893ef)
