### ISSUE TITLE
Can  the repository be tested in a computer with two GPUs?

### ISSUE THREAD

**Issue by sunjc0306** [YuliangXiu/ICON#18]
Due to the limitation of GPU memory, it is not possible to finish the test of one image on a single GPU. Can it run the test on two GPUs?

**Comment by YuliangXiu** [comment]
Not yet, maybe you can try to use a smaller marching cube resolution, change [mcube_res](https://github.com/YuliangXiu/ICON/blob/master/apps/infer.py#L66) from 512 to 256.

**Comment by sunjc0306** [comment]
Thanks for your answer! This problem has been solved with your help!
I have finished the great reconstruction result!
Looking forward to releasing your training code!

**Comment by Italy2006** [comment]
Have you solved this problem? I looked at the source code, and the value of this place is already 128. My GPU memory is only 8G, is there any way to solve it?
