### ISSUE TITLE
Can this model be run on CPU only?

### ISSUE THREAD

**Issue by kumarsh1** [YuliangXiu/ICON#180]
I am trying to run this model locally on CPU, and don't have NVIDIA Card. Can I run even inference on this type of setup?

**Comment by YuliangXiu** [comment]
ICON does not support CPU inference for now. All the models are trained and tested on GPUs.

But on the other hand, "CPU inference" is basically an engineering job for ICON, I guess it won't cost much time. Any pull requests are welcome.

**Comment by LeoMyMe** [comment]
That's good.

**Comment by kumarsh1** [comment]
Okay got it, thanks
