### ISSUE TITLE
Does ICON use gt SMPL fits during testing on CAPE dataset?

### ISSUE THREAD

**Issue by Zhangjzh** [YuliangXiu/ICON#181]
From my understanding, ICON uses gt SMPL fits to render normal maps during training. It means that all the images under thuman2_36views folder are obtained from gt data. 
However, I don't know whether gt SMPL fits are used during generating CAPE test set. Are the images under cape_3views obtained from gt data too?

**Comment by YuliangXiu** [comment]
Yes, gt-SMPL is also used for creating CAPE test set.

**Comment by Zhangjzh** [comment]
> Yes, gt-SMPL is also used to create CAPE test.

Thanks for your reply.  But I am a bit confused. Shouldn't ICON use HPS estimated SMPL to guide the model to predict normal maps. If gt-SMPL is used, there is no need to refine the SMPL mesh.

**Comment by YuliangXiu** [comment]
> > Yes, gt-SMPL is also used to create CAPE test.
> 
> Thanks for your reply. But I am a bit confused. Shouldn't ICON use HPS estimated SMPL to guide the model to predict normal maps. If gt-SMPL is used, there is no need to refine the SMPL mesh.

The SMPL refinement is applied on in-the-wild images, where gt-SMPL is not available. When it comes to quantitative evaluation, the use of gt-SMPL could ensure that the improvement of reconstruction quality ONLY comes from the method itself.

**Comment by Zhangjzh** [comment]
> > > Yes, gt-SMPL is also used to create CAPE test.
> > 
> > 
> > Thanks for your reply. But I am a bit confused. Shouldn't ICON use HPS estimated SMPL to guide the model to predict normal maps. If gt-SMPL is used, there is no need to refine the SMPL mesh.
> 
> The SMPL refinement is applied on in-the-wild images, where gt-SMPL is not available. When it comes to quantitative evaluation, the use of gt-SMPL could ensure that, the improvement of reconstruction quality **ONLY** comes from the method itself. Or to say, given the same perfect SMPL fit, how well do these methods perform?

Thanks for your help again! I kinda understand.
By the way, If I want to concatenate the normal map with other feature maps, should I change the hourglass_dim of the filter?

**Comment by YuliangXiu** [comment]
> 



> > > > Yes, gt-SMPL is also used to create CAPE test.
> > > 
> > > 
> > > Thanks for your reply. But I am a bit confused. Shouldn't ICON use HPS estimated SMPL to guide the model to predict normal maps. If gt-SMPL is used, there is no need to refine the SMPL mesh.
> > 
> > 
> > The SMPL refinement is applied on in-the-wild images, where gt-SMPL is not available. When it comes to quantitative evaluation, the use of gt-SMPL could ensure that, the improvement of reconstruction quality **ONLY** comes from the method itself. Or to say, given the same perfect SMPL fit, how well do these methods perform?
> 
> Thanks for your help again! I kinda understand. By the way, If I want to concatenate the normal map with other feature maps, should I change the hourglass_dim of the filter?

Nope, `hougrlass_dim` refers to the output dimension of Hourglass Encoder. You could check [HGPIFuNet.py](https://github.com/YuliangXiu/ICON/blob/master/lib/net/HGPIFuNet.py#L161) to know how these config attributes work.

**Comment by Zhangjzh** [comment]
> > 
> 
> > > > > Yes, gt-SMPL is also used to create CAPE test.
> > > > 
> > > > 
> > > > Thanks for your reply. But I am a bit confused. Shouldn't ICON use HPS estimated SMPL to guide the model to predict normal maps. If gt-SMPL is used, there is no need to refine the SMPL mesh.
> > > 
> > > 
> > > The SMPL refinement is applied on in-the-wild images, where gt-SMPL is not available. When it comes to quantitative evaluation, the use of gt-SMPL could ensure that, the improvement of reconstruction quality **ONLY** comes from the method itself. Or to say, given the same perfect SMPL fit, how well do these methods perform?
> > 
> > 
> > Thanks for your help again! I kinda understand. By the way, If I want to concatenate the normal map with other feature maps, should I change the hourglass_dim of the filter?
> 
> Nope, `hougrlass_dim` refers to the output dimension of Hourglass Encoder. You could check [HGPIFuNet.py](https://github.com/YuliangXiu/ICON/blob/master/lib/net/HGPIFuNet.py#L161) to know how these config attributes work.
> 
> Actually, I have already concatenated the normal+rgb in [icon-filter.yaml](https://github.com/YuliangXiu/ICON/blob/master/configs/icon-filter.yaml#L15).

Thank you very much! Have a nice day!
