### ISSUE TITLE
Should I resume checkpoint of normal and MLP if I want to train my own model?

### ISSUE THREAD

**Issue by y6216886** [YuliangXiu/ICON#182]
From file configs/train/icon-filter.yaml, I found you resume two checkpoint by default via the following code:
```
resume_path: "./data/ckpt/icon-filter.ckpt"
normal_path: "./data/ckpt/normal.ckpt"
```
If I want to train my model from scratch, should I change "resume_path" and "normal_path" to None?

**Comment by y6216886** [comment]
By the way, should I train the normal net first or train the MLP first?

**Comment by YuliangXiu** [comment]
> From file configs/train/icon-filter.yaml, I found you resume two checkpoint by default via the following code:
> 
> ```
> resume_path: "./data/ckpt/icon-filter.ckpt"
> normal_path: "./data/ckpt/normal.ckpt"
> ```
> 
> If I want to train my model from scratch, should I change "resume_path" and "normal_path" to None?

Yes

**Comment by YuliangXiu** [comment]
> By the way, should I train the normal net first or train the MLP first?

They could be trained separately, for MLP part, use GT normal instead of predicted normals.

**Comment by Zhangjzh** [comment]
> > From file configs/train/icon-filter.yaml, I found you resume two checkpoint by default via the following code:
> > ```
> > resume_path: "./data/ckpt/icon-filter.ckpt"
> > normal_path: "./data/ckpt/normal.ckpt"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If I want to train my model from scratch, should I change "resume_path" and "normal_path" to None?
> 
> Yes



> > From file configs/train/icon-filter.yaml, I found you resume two checkpoint by default via the following code:
> > ```
> > resume_path: "./data/ckpt/icon-filter.ckpt"
> > normal_path: "./data/ckpt/normal.ckpt"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If I want to train my model from scratch, should I change "resume_path" and "normal_path" to None?
> 
> Yes

I set "resume_path" and "normal_path" to None to train the model, but I got cuda out of memory error.
```yaml
resume_path: ""
normal_path: ""
```
![QQ图片20230226151815](https://user-images.githubusercontent.com/49779683/221397593-8e17943c-9bde-47e0-a58c-e01def2d1928.png)
If I load the pre-trained MLP and normal model to train, it works well. I'm confused that shouldn't the model cost the same GPU memory whether loading pre-trained model or not?

**Comment by YuliangXiu** [comment]
@Zhangjzh This is quite weird, maybe you can check [train_util.py#L80](https://github.com/YuliangXiu/ICON/blob/master/lib/common/train_util.py#L80) to filter out unused sub-nets.
