### ISSUE TITLE
Why my testing results are better than the reported results?

### ISSUE THREAD

**Issue by Zhangjzh** [YuliangXiu/ICON#183]
I followed the instructions to evaluate on the cape dataset and got following results, Chamfer: 0.993, P2S: 0.918, Normal: 0.060. I used the released model icon-nofilter.ckpt and normal.ckpt.
![QQ图片20230224102311](https://user-images.githubusercontent.com/49779683/221076663-10778879-b1f6-491b-abe4-1e9013c7bc53.png)
However, according to to paper, the results should be Chamfer: 1.142, P2S: 1.065, Normal: 0.066. I don't know why I can't get the reported results, could you please give some suggestions about what I might have done wrong?

**Comment by Zhangjzh** [comment]
By the way, I noticed that the Normal network is not used when there was clothed normals as input. 
```python
                    if (
                        "normal_F" not in in_tensor_dict.keys() or
                        "normal_B" not in in_tensor_dict.keys()
                    ):
                        (nmlF, nmlB) = self.normal_filter(in_tensor_dict)
                    else:
                        nmlF = in_tensor_dict["normal_F"]
                        nmlB = in_tensor_dict["normal_B"]
```
Does ICON use gt rendered clothed normals during testing instead of Normal network predicted clothed normals?

**Comment by YuliangXiu** [comment]
Nope, you have done correctly. The CAPE dataset was updated to fix some misalignment bugs. I will update the numbers in arXiv in the near future.

ICON uses normal predictions during testing, I think this is a bug for `master` branch, you could see that these lines are commented in 'dev' branch, [HGPIFuNet.py](https://github.com/YuliangXiu/ICON/blob/dev/lib/net/HGPIFuNet.py#L182).

**Comment by Zhangjzh** [comment]
> Nope, you have done correctly. The CAPE dataset was updated to fix some misalignment bugs. I will update the numbers in arXiv in the near future. Also, all the released checkpoints (`.ckpt`) are trained on 4K scans (see AGORA [1]).
> 
> ICON uses normal predictions during testing, I think this is a bug for `master` branch, you could see that these lines are commented in `dev` branch, [HGPIFuNet.py](https://github.com/YuliangXiu/ICON/blob/dev/lib/net/HGPIFuNet.py#L182).
> 
> [1] Patel P, Huang C H P, Tesch J, et al. AGORA: Avatars in geography optimized for regression analysis[C]//Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition. 2021: 13468-13478.

Thank you very much for your kind reply!

**Comment by Yuhuoo** [comment]
> I followed the instructions to evaluate on the cape dataset and got following results, Chamfer: 0.993, P2S: 0.918, Normal: 0.060. I used the released model icon-nofilter.ckpt and normal.ckpt. ![QQ图片20230224102311](https://user-images.githubusercontent.com/49779683/221076663-10778879-b1f6-491b-abe4-1e9013c7bc53.png) However, according to to paper, the results should be Chamfer: 1.142, P2S: 1.065, Normal: 0.066. I don't know why I can't get the reported results, could you please give some suggestions about what I might have done wrong?

Hi, I want to know how get the final results from the easy and hard. Is this using the mean value of easy and hard ? Such as the Chamfer0.993 = (0.911(easy) + 1.087(hard)) / 2. I also want to know the meaning of easy and hard.

**Comment by Zhangjzh** [comment]
> > I followed the instructions to evaluate on the cape dataset and got following results, Chamfer: 0.993, P2S: 0.918, Normal: 0.060. I used the released model icon-nofilter.ckpt and normal.ckpt. ![QQ图片20230224102311](https://user-images.githubusercontent.com/49779683/221076663-10778879-b1f6-491b-abe4-1e9013c7bc53.png) However, according to to paper, the results should be Chamfer: 1.142, P2S: 1.065, Normal: 0.066. I don't know why I can't get the reported results, could you please give some suggestions about what I might have done wrong?
> 
> Hi, I want to know how get the final results from the easy and hard. Is this using the mean value of easy and hard ? Such as the Chamfer0.993 = (0.911(easy) + 1.087(hard)) / 2. Furthermore, I also want to know the meaning of easy and hard.

I modified test_epoch_end function in ICON.py. But I am not sure whether this is correct.
```python
        accu_outputs = accumulate(
            outputs,
            rot_num=3,
            split={
                "cape": (0, 150)
            },
        )
```
