### ISSUE TITLE
A little smplxs are unaligned to scans

### ISSUE THREAD

**Issue by gushengbo** [YuliangXiu/ICON#184]
I find that most of the smplxs are aligned to scans, such as 0008:
![19243e094d50520976b606ae25e11b2](https://user-images.githubusercontent.com/122679046/222125956-06bc4aef-67c4-425f-afc7-4f466d586e4e.png)
but I find that a litter smplxs are unaligned to scans, such as 0069.  could you tell me why? Thank you very much!
![7ff08b1470fee3ca65d0df0d66bbd59](https://user-images.githubusercontent.com/122679046/222126220-d492c7a7-3955-4e3d-8bd1-df16b8dfaffc.png)

**Comment by YuliangXiu** [comment]
@gushengbo Have you found the way to solve it?

**Comment by gushengbo** [comment]
> @gushengbo Have you found the way to solve it?
This is the result
![image](https://user-images.githubusercontent.com/122679046/225645686-3a0a43bd-1c22-46bd-ba34-5a2648cacf9d.png)
