### ISSUE TITLE
Data description of 'smpl_cmap' and 'tedra_data'

### ISSUE THREAD

**Issue by xyyeah** [YuliangXiu/ICON#19]
Thanks for the exciting job! Can you please give some description about 'smpl_cmap' and 'tedra_data'? Cannot google too much about them and cannot find related keywords in the paper.

**Comment by YuliangXiu** [comment]
tedra_data is used by PaMIR's voxelization layer.

smpl_cmap means "3D colormap defined on canonical pose", I used this feature at the beginning but found it not that important. I will provide the pre-trained model without smpl_cmap later.
