### ISSUE TITLE
whether you have used gt_smpl to train on Thuman2.0, and whether you have used gt_smpl test on CAPE? 

### ISSUE THREAD

**Issue by gushengbo** [YuliangXiu/ICON#190]
Hi, could you tell me whether you have used gt_smpl to train on Thuman2.0, and whether you have used gt_smpl test on CAPE on this experiment? 
Thank you!
![image](https://user-images.githubusercontent.com/122679046/226159721-c4d012d5-1da0-4c0b-9db8-9abe2bccd585.png)

**Comment by YuliangXiu** [comment]
Yes, both. We use GT SMPL for training and testing. 

BTW, we have updated the CAPE testset with more well-aligned SMPL and clean background. Now these errors should be much smaller.
