### ISSUE TITLE
Thuman2 Data preprossess

### ISSUE THREAD

**Issue by glorioushonor** [YuliangXiu/ICON#192]
Good job！I would like to know why I get the training data like this. Could you please give me some help?
![屏幕截图 2023-03-26 180749](https://user-images.githubusercontent.com/120625228/227774240-410f9d65-fba2-44a4-897e-4dd1124f5e14.jpg)

**Comment by YuliangXiu** [comment]
You can re-run the data generation scripts, the misaligned objs will be replaced with the well-aligned ones.

https://github.com/YuliangXiu/ICON/issues/164#issuecomment-1374828826
