### ISSUE TITLE
color for clothes and skin

### ISSUE THREAD

**Issue by Yisng** [YuliangXiu/ICON#195]
How to draw the original color for clothes and skin

**Comment by YuliangXiu** [comment]
ICON only supports half-texture obtained from single image, see https://github.com/YuliangXiu/ICON/issues/49#issuecomment-1109635487

**Comment by YuliangXiu** [comment]
We recently released a new work, TeCH. Given a single image, TeCH could produce a **full textured avatar** with both intricate geometric details and consistent high-quality texture.

<div align="center">
    <video autoplay loop muted src="https://github.com/huangyangyi/TeCH/assets/7944350/f8fc55ed-9cbe-4b5f-bd1d-237396360713" type=video/mp4>
    </video>
  </div>

Homepage: https://huangyangyi.github.io/TeCH/
