### ISSUE TITLE
missing keypoints data

### ISSUE THREAD

**Issue by lyk412** [YuliangXiu/ICON#196]
hi, I tried to test the performance of **icon-keypoint** with your `icon-keypoint.ckpt`, but I got an error message as follows:

>   File "/home/xxx/ICON/lib/net/HGPIFuNet.py", line 458, in query
>     kpt_feat = self.sp_encoder.forward(
>   File "/home/xxx/ICON/lib/net/spatial.py", line 71, in forward
>     K = kptxyz.shape[1]
> AttributeError: 'NoneType' object has no attribute 'shape'

It seems that the keypoint information is missing, and the `kptxyz` is `self.smpl_feat_dict["smpl_joint"]`. I checked the file `lib/dataset/PIFuDataset.py` and found that there is no relevant information about `smpl_joint`. 
So how can I obtain it for training and testing **icon-keypoint**? Thanks!!!

**Comment by YuliangXiu** [comment]
The joints come from SMPL model, you can check [render_single.py#L99](https://github.com/YuliangXiu/ICON/blob/dev/scripts/render_single.py#L99) to export joints.
