### ISSUE TITLE
visibility compute speed

### ISSUE THREAD

**Issue by lucas-jay** [YuliangXiu/ICON#198]
Hello, I'm running 
`python -m scripts.visibility_batch -out_dir data/` to do visibility computation, but i found it quite slow.

<img width="634" alt="image" src="https://user-images.githubusercontent.com/71963429/230939182-fc66cb5f-276b-401a-ad22-09b988b659ad.png">

before I've run
`python -m scripts.render_batch -headless -out_dir data/`,
I set ms_rate = 1.0 and take about 1h to finish it.
I wonder if there is any way to improve visibility computation speed, thank you very much : )

**Comment by YuliangXiu** [comment]
The visibility computation requires GPU, it will be extremely slow for CPU.

**Comment by z-z-zhao** [comment]
![速度](https://user-images.githubusercontent.com/57577944/234511835-ee0da20c-9c0d-4ee7-9f6e-74ed070a4e9a.jpg)
我使用了GPU，你可以看到我的GPU使用率是100%，可是速度依然很慢，大概10多分钟处理一个模型。

**Comment by z-z-zhao** [comment]
I used GPU, you can see that my GPU usage is 100%, but it is still very slow, about 10 minutes  to process a model.

**Comment by YuliangXiu** [comment]
> I used GPU, you can see that my GPU usage is 100%, but it is still very slow, about 10 minutes to process a model.

It's normal, on my machine (Quadro RTX 5000, CUDA 11.4), it takes 13 min per subject, we need to compute 36 views for every subject, so roughly `20 sec / view`.
