### ISSUE TITLE
scan to fit?

### ISSUE THREAD

**Issue by Leestronger** [YuliangXiu/ICON#199]
Hello, I would like to ask if you know any better ways to convert from scan to smpl/smplx model?

**Comment by YuliangXiu** [comment]
You can check [avatarizer.py](https://github.com/YuliangXiu/ECON/blob/master/apps/avatarizer.py)

This file converts the ECON reconstruction into a SMPL-X compatible model, which can be driven by SMPL-X pose params.

**Comment by Leestronger** [comment]
Thank you so much ! I will check it!
