### ISSUE TITLE
Some questions about training and result

### ISSUE THREAD

**Issue by glorioushonor** [YuliangXiu/ICON#200]
Hello, I'd like to ask you some questions about training.
1. When I reproduce PaMir and PIFu with the same architecture as ICON, do I only need to run the following instructions to train MLP network?  Is the nomal network shared, no need to retrain the nomal network for PaMir and PIFu，right？
`CUDA_VISIBLE_DEVICES=0 python -m apps.train -cfg ./configs/train/pamir.yaml`
`CUDA_VISIBLE_DEVICES=0 python -m apps.train -cfg ./configs/train/pifu.yaml`

2. Why are the 2nd and 4th normal pictures of ICON-nofilter, PaMir, PIFu so bad compared to the 1st and 3rd normal pictures?The following figures are the results of ICON-nofilter, PaMir, and PIFu, in order.
![image](https://user-images.githubusercontent.com/120625228/231802543-6e49af7d-25d4-430e-a72c-9b1e83b3f44b.png)
![image](https://user-images.githubusercontent.com/120625228/231802954-285d2b8f-ac0e-4c9d-870f-b9da0d2aef1f.png)
![image](https://user-images.githubusercontent.com/120625228/231803052-b942421b-70e2-44de-a8ab-6e118ceafa90.png)

**Comment by YuliangXiu** [comment]
1. Yes, you can directly use the pretrained normal network during training.
2. Because the input only contains the front and back normal maps, so their corresponding reconstructions are better than the left and right side views.

**Comment by glorioushonor** [comment]
> 1. Yes, you can directly use the pretrained normal network during training.
> 2. Because the input only contains the front and back normal maps, so their corresponding reconstructions are better than the left and right side views.

Thanks for your kind reply. But I have one question about one point in your answer. Is resuming pretrained normal network necessary for training MLP network? Because I trained these two networks separately and set `resume_path: ""`and `normal_path: ""`.
I guess you recommended me to use the pretrained normal network during training the MLP network **in order to get the right visualization result** after training MLP network, right?

**Comment by YuliangXiu** [comment]
> > 1. Yes, you can directly use the pretrained normal network during training.
> > 2. Because the input only contains the front and back normal maps, so their corresponding reconstructions are better than the left and right side views.
> 
> Thanks for your kind reply. But I have one question about one point in your answer. Is resuming pretrained normal network necessary for training MLP network? Because I trained these two networks separately and set `resume_path: ""`and `normal_path: ""`. I guess you recommended me to use the pretrained normal network during training the MLP network **in order to get the right visualization result** after training MLP network, right?

Normal network is to estimate the normal maps, if the GT normal maps are already available, you don't need the pretrained model. I didn't use it to train MLP, but you can have a try, I am not sure whether it will improve the reconstruction or not.
