### ISSUE TITLE
Potential error or a typo in one of the loss functions in infer.py

### ISSUE THREAD

**Issue by EgSam** [YuliangXiu/ICON#205]
In infer.py, I think there is a typo as in the loss 

losses["normal"]["value"] = (diff_F_smpl + diff_F_smpl).mean()
it should be :
losses["normal"]["value"] = (diff_F_smpl + diff_B_smpl).mean()

if this is the case, you may get slightly better results

**Comment by YuliangXiu** [comment]
Yes, it should be, could you make a `pull request` for it? I will merge it, and you will be listed as contributors as well.

**Comment by EgSam** [comment]
Thank you !
