### ISSUE TITLE
The dimension of Fp

### ISSUE THREAD

**Issue by glorioushonor** [YuliangXiu/ICON#212]
Hi. I'm sorry to bother you. I know F_s (P) is a 1-dimension signed distance; It is shown that [F_n^b (P), F_n^c (P)] is 6-dimensiona in the figture. It is because F_n^b (P) and F_n^c (P) are both space vectors, so the total dimension is 6(3 plus 3)? I didn't find the relevant content in the code, so I came to you to confirm.

**Comment by YuliangXiu** [comment]
Yes, $N_{cloth} \in \mathbf{R}^{3 \times H \times W}, N_{body} \in \mathbf{R}^{3 \times H \times W}, {SDF}_{body} \in \mathbf{R}^{1}$, the input dimension of MLP is 3+3+1=7
