### ISSUE TITLE
求助大佬一个问题，关于运行render时发送的错误

### ISSUE THREAD

**Issue by BlackGrain** [YuliangXiu/ICON#217]
在运行以下代码时发送报错，
```
python -m scripts.render_batch -headless -out_dir data/

报错：
multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x7f9cd8ac4ee0>'. 
Reason: 'ValueError('ctypes objects containing pointers cannot be pickled')'

```
根据网上的方法，将`PROC_PER_GPU = mp.cpu_count() // NUM_GPUS` 改为`PROC_PER_GPU = 0`，同时`NUM_GPUS`设置为1。

之后可以运行，但是进度卡在，如下，同时GPU也未在工作状态
```
Start Rendering thuman2 with 36 views, 512x512 size.
Output dir: data//thuman2_36views
Rendering types: ['light', 'normal']
  0%|                    | 0/526 [00:00<?, ?it/s]
```

请问我该如何成功运行这个？

**Comment by YuliangXiu** [comment]
Maybe https://github.com/YuliangXiu/ICON/issues/62#issuecomment-1134315213 could resolve this problem.

**Comment by R33333** [comment]
> 在运行以下代码时发送报错，
> 
> ```
> python -m scripts.render_batch -headless -out_dir data/
> 
> 报错：
> multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x7f9cd8ac4ee0>'. 
> Reason: 'ValueError('ctypes objects containing pointers cannot be pickled')'
> ```
> 
> 根据网上的方法，将`PROC_PER_GPU = mp.cpu_count() // NUM_GPUS` 改为`PROC_PER_GPU = 0`，同时`NUM_GPUS`设置为1。
> 
> 之后可以运行，但是进度卡在，如下，同时GPU也未在工作状态
> 
> ```
> Start Rendering thuman2 with 36 views, 512x512 size.
> Output dir: data//thuman2_36views
> Rendering types: ['light', 'normal']
>   0%|                    | 0/526 [00:00<?, ?it/s]
> ```
> 
> 请问我该如何成功运行这个？

兄弟，你解决了吗，我重新安装了pyembree和trimesh，尝试了好几个版本还是不行

**Comment by Dragon2938734** [comment]
我也一样，重新安装了pyembree和trimesh也不行，感觉是不是multiprocessing的问题啊

**Comment by YuxuanSnow** [comment]
I faced the same issue, I confirm the problem is at `mesh.ray.intersect_any`. The reason is because it doesn't use pyembree but the default trimesh intersection function.

You have to install pyembree properly. Please refer to this: https://github.com/YuxuanSnow/ICON/blob/yuxuan_branch/docs/dataset.md

After your install the proper embree and trimesh call them during intersect function, it takes about 0.5s to process 3M points.

**Comment by yangqinhui0423** [comment]
> I faced the same issue, I confirm the problem is at `mesh.ray.intersect_any`. The reason is because it doesn't use pyembree but the default trimesh intersection function.
> 
> You have to install pyembree properly. Please refer to this: https://github.com/YuxuanSnow/ICON/blob/yuxuan_branch/docs/dataset.md
> 
> After your install the proper embree and trimesh call them during intersect function, it takes about 0.5s to process 3M points.

Hello! Could you please tell me your version of embree, pyembree and trimesh? I tried to uninstall and reinstall pyembree and trimesh but it doesn't work.

**Comment by lywudi** [comment]
> > 在运行以下代码时发送报错，
> > ```
> > python -m scripts.render_batch -headless -out_dir data/
> > 
> > 报错：
> > multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x7f9cd8ac4ee0>'. 
> > Reason: 'ValueError('ctypes objects containing pointers cannot be pickled')'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 根据网上的方法，将`PROC_PER_GPU = mp.cpu_count() // NUM_GPUS` 改为`PROC_PER_GPU = 0`，同时`NUM_GPUS`设置为1。
> > 之后可以运行，但是进度卡在，如下，同时GPU也未在工作状态
> > ```
> > Start Rendering thuman2 with 36 views, 512x512 size.
> > Output dir: data//thuman2_36views
> > Rendering types: ['light', 'normal']
> >   0%|                    | 0/526 [00:00<?, ?it/s]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 请问我该如何成功运行这个？
> 
> 兄弟，你解决了吗，我重新安装了pyembree和trimesh，尝试了好几个版本还是不行

解决问题了吗兄弟而且我的thuman2/smpl和smplx和他的也不一样

**Comment by R33333** [comment]
> > > 在运行以下代码时发送报错，
> > > ```
> > > python -m scripts.render_batch -headless -out_dir data/
> > > 
> > > 报错：
> > > multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x7f9cd8ac4ee0>'. 
> > > Reason: 'ValueError('ctypes objects containing pointers cannot be pickled')'
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 根据网上的方法，将`PROC_PER_GPU = mp.cpu_count() // NUM_GPUS` 改为`PROC_PER_GPU = 0`，同时`NUM_GPUS`设置为1。
> > > 之后可以运行，但是进度卡在，如下，同时GPU也未在工作状态
> > > ```
> > > Start Rendering thuman2 with 36 views, 512x512 size.
> > > Output dir: data//thuman2_36views
> > > Rendering types: ['light', 'normal']
> > >   0%|                    | 0/526 [00:00<?, ?it/s]
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 请问我该如何成功运行这个？
> > 
> > 
> > 兄弟，你解决了吗，我重新安装了pyembree和trimesh，尝试了好几个版本还是不行
> 
> 解决问题了吗兄弟而且我的thuman2/smpl和smplx和他的也不一样

我最后没有用多进程，一个一个顺序处理的，虽然慢，但是能运行了

**Comment by lywudi** [comment]
> > > > 在运行以下代码时发送报错，
> > > > ```
> > > > python -m scripts.render_batch -headless -out_dir data/
> > > > 
> > > > 报错：
> > > > multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x7f9cd8ac4ee0>'. 
> > > > Reason: 'ValueError('ctypes objects containing pointers cannot be pickled')'
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 根据网上的方法，将`PROC_PER_GPU = mp.cpu_count() // NUM_GPUS` 改为`PROC_PER_GPU = 0`，同时`NUM_GPUS`设置为1。
> > > > 之后可以运行，但是进度卡在，如下，同时GPU也未在工作状态
> > > > ```
> > > > Start Rendering thuman2 with 36 views, 512x512 size.
> > > > Output dir: data//thuman2_36views
> > > > Rendering types: ['light', 'normal']
> > > >   0%|                    | 0/526 [00:00<?, ?it/s]
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 请问我该如何成功运行这个？
> > > 
> > > 
> > > 兄弟，你解决了吗，我重新安装了pyembree和trimesh，尝试了好几个版本还是不行
> > 
> > 
> > 解决问题了吗兄弟而且我的thuman2/smpl和smplx和他的也不一样
> 
> 我最后没有用多进程，一个一个顺序处理的，虽然慢，但是能运行了

你好可以加个联系方式交流下吗

**Comment by lywudi** [comment]
> > > > > 在运行以下代码时发送报错，
> > > > > ```
> > > > > python -m scripts.render_batch -headless -out_dir data/
> > > > > 
> > > > > 报错：
> > > > > multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x7f9cd8ac4ee0>'. 
> > > > > Reason: 'ValueError('ctypes objects containing pointers cannot be pickled')'
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > 根据网上的方法，将`PROC_PER_GPU = mp.cpu_count() // NUM_GPUS` 改为`PROC_PER_GPU = 0`，同时`NUM_GPUS`设置为1。
> > > > > 之后可以运行，但是进度卡在，如下，同时GPU也未在工作状态
> > > > > ```
> > > > > Start Rendering thuman2 with 36 views, 512x512 size.
> > > > > Output dir: data//thuman2_36views
> > > > > Rendering types: ['light', 'normal']
> > > > >   0%|                    | 0/526 [00:00<?, ?it/s]
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > 请问我该如何成功运行这个？
> > > > 
> > > > 
> > > > 兄弟，你解决了吗，我重新安装了pyembree和trimesh，尝试了好几个版本还是不行
> > > 
> > > 
> > > 解决问题了吗兄弟而且我的thuman2/smpl和smplx和他的也不一样
> > 
> > 
> > 我最后没有用多进程，一个一个顺序处理的，虽然慢，但是能运行了
> 
> 你好可以加个联系方式交流下吗



> > > > 在运行以下代码时发送报错，
> > > > ```
> > > > python -m scripts.render_batch -headless -out_dir data/
> > > > 
> > > > 报错：
> > > > multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x7f9cd8ac4ee0>'. 
> > > > Reason: 'ValueError('ctypes objects containing pointers cannot be pickled')'
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 根据网上的方法，将`PROC_PER_GPU = mp.cpu_count() // NUM_GPUS` 改为`PROC_PER_GPU = 0`，同时`NUM_GPUS`设置为1。
> > > > 之后可以运行，但是进度卡在，如下，同时GPU也未在工作状态
> > > > ```
> > > > Start Rendering thuman2 with 36 views, 512x512 size.
> > > > Output dir: data//thuman2_36views
> > > > Rendering types: ['light', 'normal']
> > > >   0%|                    | 0/526 [00:00<?, ?it/s]
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 请问我该如何成功运行这个？
> > > 
> > > 
> > > 兄弟，你解决了吗，我重新安装了pyembree和trimesh，尝试了好几个版本还是不行
> > 
> > 
> > 解决问题了吗兄弟而且我的thuman2/smpl和smplx和他的也不一样
> 
> 我最后没有用多进程，一个一个顺序处理的，虽然慢，但是能运行了

可以请教一下怎么不用多线程的啊

**Comment by R33333** [comment]
> > > > > > 在运行以下代码时发送报错，
> > > > > > ```
> > > > > > python -m scripts.render_batch -headless -out_dir data/
> > > > > > 
> > > > > > 报错：
> > > > > > multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x7f9cd8ac4ee0>'. 
> > > > > > Reason: 'ValueError('ctypes objects containing pointers cannot be pickled')'
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > >     
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >     
> > > > > >   
> > > > > > 根据网上的方法，将`PROC_PER_GPU = mp.cpu_count() // NUM_GPUS` 改为`PROC_PER_GPU = 0`，同时`NUM_GPUS`设置为1。
> > > > > > 之后可以运行，但是进度卡在，如下，同时GPU也未在工作状态
> > > > > > ```
> > > > > > Start Rendering thuman2 with 36 views, 512x512 size.
> > > > > > Output dir: data//thuman2_36views
> > > > > > Rendering types: ['light', 'normal']
> > > > > >   0%|                    | 0/526 [00:00<?, ?it/s]
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > >     
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >     
> > > > > >   
> > > > > > 请问我该如何成功运行这个？
> > > > > 
> > > > > 
> > > > > 兄弟，你解决了吗，我重新安装了pyembree和trimesh，尝试了好几个版本还是不行
> > > > 
> > > > 
> > > > 解决问题了吗兄弟而且我的thuman2/smpl和smplx和他的也不一样
> > > 
> > > 
> > > 我最后没有用多进程，一个一个顺序处理的，虽然慢，但是能运行了
> > 
> > 
> > 你好可以加个联系方式交流下吗
> 
> > > > > 在运行以下代码时发送报错，
> > > > > ```
> > > > > python -m scripts.render_batch -headless -out_dir data/
> > > > > 
> > > > > 报错：
> > > > > multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x7f9cd8ac4ee0>'. 
> > > > > Reason: 'ValueError('ctypes objects containing pointers cannot be pickled')'
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > 根据网上的方法，将`PROC_PER_GPU = mp.cpu_count() // NUM_GPUS` 改为`PROC_PER_GPU = 0`，同时`NUM_GPUS`设置为1。
> > > > > 之后可以运行，但是进度卡在，如下，同时GPU也未在工作状态
> > > > > ```
> > > > > Start Rendering thuman2 with 36 views, 512x512 size.
> > > > > Output dir: data//thuman2_36views
> > > > > Rendering types: ['light', 'normal']
> > > > >   0%|                    | 0/526 [00:00<?, ?it/s]
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > 请问我该如何成功运行这个？
> > > > 
> > > > 
> > > > 兄弟，你解决了吗，我重新安装了pyembree和trimesh，尝试了好几个版本还是不行
> > > 
> > > 
> > > 解决问题了吗兄弟而且我的thuman2/smpl和smplx和他的也不一样
> > 
> > 
> > 我最后没有用多进程，一个一个顺序处理的，虽然慢，但是能运行了
> 
> 可以请教一下怎么不用多线程的啊

你微信多少，我加你

**Comment by lywudi** [comment]
L_Yu_0688

&nbsp;


寸心白衫
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ren ***@***.***&gt;; 
发送时间: 2024年11月14日(星期四) 晚上7:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [YuliangXiu/ICON] 求助大佬一个问题，关于运行render时发送的错误 (Issue #217)














       
在运行以下代码时发送报错，
 python -m scripts.render_batch -headless -out_dir data/ 报错： multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x7f9cd8ac4ee0&gt;'.  Reason: 'ValueError('ctypes objects containing pointers cannot be pickled')'  
根据网上的方法，将PROC_PER_GPU = mp.cpu_count() // NUM_GPUS 改为PROC_PER_GPU = 0，同时NUM_GPUS设置为1。
 之后可以运行，但是进度卡在，如下，同时GPU也未在工作状态
 Start Rendering thuman2 with 36 views, 512x512 size. Output dir: data//thuman2_36views Rendering types: ['light', 'normal']   0%|                    | 0/526 [00:00<?, ?it/s]  
请问我该如何成功运行这个？
  
兄弟，你解决了吗，我重新安装了pyembree和trimesh，尝试了好几个版本还是不行
  
解决问题了吗兄弟而且我的thuman2/smpl和smplx和他的也不一样
  
我最后没有用多进程，一个一个顺序处理的，虽然慢，但是能运行了
  
你好可以加个联系方式交流下吗
      
在运行以下代码时发送报错，
 python -m scripts.render_batch -headless -out_dir data/ 报错： multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x7f9cd8ac4ee0&gt;'.  Reason: 'ValueError('ctypes objects containing pointers cannot be pickled')'  
根据网上的方法，将PROC_PER_GPU = mp.cpu_count() // NUM_GPUS 改为PROC_PER_GPU = 0，同时NUM_GPUS设置为1。
 之后可以运行，但是进度卡在，如下，同时GPU也未在工作状态
 Start Rendering thuman2 with 36 views, 512x512 size. Output dir: data//thuman2_36views Rendering types: ['light', 'normal']   0%|                    | 0/526 [00:00<?, ?it/s]  
请问我该如何成功运行这个？
  
兄弟，你解决了吗，我重新安装了pyembree和trimesh，尝试了好几个版本还是不行
  
解决问题了吗兄弟而且我的thuman2/smpl和smplx和他的也不一样
  
我最后没有用多进程，一个一个顺序处理的，虽然慢，但是能运行了
  
可以请教一下怎么不用多线程的啊
  
你微信多少，我加你
