### ISSUE TITLE
Question about training ICON with custom scans

### ISSUE THREAD

**Issue by mylee95** [YuliangXiu/ICON#218]
Hi, sorry to interrupt you but I have question about training ICON with custom dataset. 

I have custom scans and SMPL parameters fitted with them([with this open source](https://github.com/ZhengZerong/MultiviewSMPLifyX)), and tried to generate train data for ICON, but found that your data generation code only accepts SMPL-X parameters that contain left/right hand poses and facial poses in pkl file, according to lib/renderer/mesh.py code. 

In issue #199 you commented to try using ECON for making data from scans, but I'm not sure how much reliable ECON is, since it only uses single image to estimate SMPL-X parameters. 

I was curious how did you get SMPL-X fits for other datasets like RenderPeople, which doesn't have SMPL-X fits on its own, when you were training ICON for the paper? Did you just make pseudo SMPL-X fits with other open sources that estimates SMPL-X parameters with single image? Do they have enough quality to train models like ICON?

**Comment by YuliangXiu** [comment]
You can find the SMPL-X fits of RenderPeople from AGORA dataset.

Same issue: https://github.com/YuliangXiu/ECON/issues/62

Our internal fitting pipeline is similar to [MultiviewSMPLifyX](https://github.com/ZhengZerong/MultiviewSMPLifyX), but there is no plan to release. 

As for the poses of hand and face, you can edit the class of `SMPLX` in ICON, to make it compatible with your setting. ICON supports any parametric body models as long as these models could produce mesh-based body as input.

**Comment by mylee95** [comment]
Thank you for quick respond! I'll try editting the SMPLX class, and share if it works :D
