### ISSUE TITLE
Can you share the repo link or code of the ARCH and ARCH++？

### ISSUE THREAD

**Issue by Yuhuoo** [YuliangXiu/ICON#220]
Hi, excuse me, could you please help provide the code or link of ARCH and ARCH++? Can't find relevant information on the Internet, and “https://tonghehehe.com/archpp” is invalid now.

**Comment by YuliangXiu** [comment]
Meta has not released the official ARCH(++). You could send email to the authors to ask for help in testing, or use unofficial re-implementation [ARCH](https://github.com/TingtingLiao/ARCH).
