### ISSUE TITLE
scale and beta in cape

### ISSUE THREAD

**Issue by naivate** [YuliangXiu/ICON#222]
excuse me! There are no parameters for beta and scale in the cape dataset, where can I get them from。

**Comment by YuxuanSnow** [comment]
Hi, the betas of minimal body shape is available in cape dataset. Please find it in download page of cape website.

**Comment by YuxuanSnow** [comment]
@YuliangXiu Issue is addressed ;)

**Comment by YuliangXiu** [comment]
> @YuliangXiu Issue is addressed ;)

Thanks for Yuxuan's great effort.
