### ISSUE TITLE
The code to obtain 4-views rendered results of the Cape dataset

### ISSUE THREAD

**Issue by glorioushonor** [YuliangXiu/ICON#233]
Good job! I would like to know the code to obtain rendered results and visibility results of the Cape dataset, as I am interested in obtaining 4-views rendered results of the Cape dataset.  Thank you.

**Comment by YuliangXiu** [comment]
Please check [dataset.md](https://github.com/YuliangXiu/ICON/blob/master/docs/dataset.md) to know the rendering procedure

**Comment by glorioushonor** [comment]
> Please check [dataset.md](https://github.com/YuliangXiu/ICON/blob/master/docs/dataset.md) to know the rendering procedure
So, the THuman2.0 dataset and the CAPE dataset share the same rendering pipeline? 
However, the CAPE dataset does not have `tex_file = f'./data/{dataset}/scans/{subject}/material0.jpeg'` and `fit_file = f'./data/{dataset}/{smpl_type}/{subject}.pkl'`.

**Comment by YuliangXiu** [comment]
Yes, the textured scans of CAPE are not publicly available.

**Comment by glorioushonor** [comment]
> Yes, the textured scans of CAPE are not publicly available.
So I cannot render the CAPE dataset according to my own needs? 
In fact, I am trying to reproduce the work of D_if, but my test results differ from the paper to some extent. 
So, I looked into the reasons. I found that Xueting Yang rendered the CAPE dataset from four viewpoints, but I can only download the rendering results of three viewpoints. Could this be a reason for my poorer test results?
![1697382465664](https://github.com/YuliangXiu/ICON/assets/120625228/7057220b-e477-483e-b399-8cd37ab77227)
By the way, is there any way to get the 4-view rendering result of CAPE?

**Comment by YuliangXiu** [comment]
I think this is a typo, D-IF does evaluation under the same setting as ICON with 3 views (0, 120, 240), see [PIFuDataset.py#L99](https://github.com/psyai-net/D-IF_release/blob/main/lib/dataset/PIFuDataset.py#L99). 

All these testing data could be downloaded from [CAPE](https://cape.is.tue.mpg.de/download.php). No need to re-render them.

I will ask Xueting to update the arXiv later. Thanks for correcting us.
