### ISSUE TITLE
How can I get the model trainable parameters information?

### ISSUE THREAD

**Issue by Yuhuoo** [YuliangXiu/ICON#236]
During training, I noticed that the trainable parameters of the model were printed in the console. Could you please let me know how this is printed? I couldn't find this print code in the project.
![1700573042415_85201D53-5F66-4bbf-962C-0A86CDCB1AE3](https://github.com/YuliangXiu/ICON/assets/91204817/e76df88d-f9c8-4735-bf00-12c8cabee5fc)

**Comment by YuliangXiu** [comment]
This should be a built-in feature of PyTorch-Lightning. You could check the document of PL for more details.
