### ISSUE TITLE
A question about the environment

### ISSUE THREAD

**Issue by yangqinhui0423** [YuliangXiu/ICON#238]
Hello, I met a problem when I run"conda env create -f environment.yaml" and I get error as follows:
![111](https://github.com/YuliangXiu/ICON/assets/112925344/86ac62b2-9c7c-4e59-ba70-2accd6510a31)

I tried to install cuda 11.3，but after that , when I tried to install PyTorch = 1.13.0, I met error as follows:
![222](https://github.com/YuliangXiu/ICON/assets/112925344/d21578e1-801a-4aad-afca-1a1964c12b39)
Then I  follow the instruction but I cannot find the 11.3 version for pytorch-cuda.
![333](https://github.com/YuliangXiu/ICON/assets/112925344/7482898b-7703-4729-9506-4858cd12d54f)
![444](https://github.com/YuliangXiu/ICON/assets/112925344/b8a78f14-0c89-491b-a05e-7dac82211d51)

Can anyone help me?I was haunted for days.

**Comment by yangqinhui0423** [comment]
I have solved the problem. Please delete it.

**Comment by damonchang23** [comment]
@yangqinhui0423 Hi, I also met a sample problem. Can you share how solve this problem? Thank you.

**Comment by yangqinhui0423** [comment]
> @yangqinhui0423 Hi, I also met a sample problem. Can you share how solve this problem? Thank you.

I just use cuda 11.6 and pytorch-cuda 11.6, others follow the environment.yaml.
