### ISSUE TITLE
How much RAM do I need to run the demo?

### ISSUE THREAD

**Issue by yutaokuyama** [YuliangXiu/ICON#24]
Hi, thanks for your great job. I tried to try the demo and the task was killed due to lack of RAM. How much RAM do I need to run the demo?
Similarly, when I try to run the Colab demo, I get a warning that I need a lot of RAM. Is it possible to run the provided Colab demo with the free version? (Sorry I haven't tried it myself)

**Comment by YuliangXiu** [comment]
Please Use "High-RAM" runtime shape in Google Colab

[![bdm6kq.png](https://s4.ax1x.com/2022/03/05/bdm6kq.png)](https://imgtu.com/i/bdm6kq)

**Comment by YuliangXiu** [comment]
@yutaokuyama I just updated the installation scripts, colab can work well for now.

<a href='https://colab.research.google.com/drive/1-AWeWhPvCTBX0KfMtgtMk10uPU05ihoA?usp=sharing' style='padding-left: 0.5rem;'>
      <img src='https://colab.research.google.com/assets/colab-badge.svg' alt='Google Colab'>
    </a>

It is POSSIBLE to run the provided Colab demo with the free version, I tried and worked.
