### ISSUE TITLE
A question about the version of pytorch and cuda

### ISSUE THREAD

**Issue by yangqinhui0423** [YuliangXiu/ICON#241]
In the installstion.md, the environment is as follows:
![image](https://github.com/YuliangXiu/ICON/assets/112925344/830e0cbb-78d9-48ba-ad99-aba0c3c0108d)
But when I go to the pytorch official website, the pytorch 1.13.0 only supports version above CUDA 11.6.
Can I change any version of them?
![image](https://github.com/YuliangXiu/ICON/assets/112925344/e4ba3050-06de-4f9c-a750-a0c2671ed6fc)

**Comment by YuliangXiu** [comment]
ICON/ECON functions effectively as long as PyTorch, Kaolin, and PyTorch3D can be installed on your machine. There are no strict requirements, and the versions listed in the README file are specific to my local environment.
