### ISSUE TITLE
Error in Colab: No module named 'trimesh'

### ISSUE THREAD

**Issue by erikestany** [YuliangXiu/ICON#26]
Hello,

In Colab, after run

```
%cd /content/ICON/apps
!source activate icon && python infer.py -cfg ../configs/icon-filter.yaml -loop_smpl 100 -loop_cloth 0 -colab -gpu 0 -export_video
```

I get this:

/content/ICON/apps
Traceback (most recent call last):
  File "infer.py", line 23, in <module>
    import torch, trimesh
**ModuleNotFoundError: No module named 'trimesh'**

What am I doing wrong?

Thanks!

**Comment by YuliangXiu** [comment]
I just updated the installation scripts, colab can work well for now.

<a href='https://colab.research.google.com/drive/1-AWeWhPvCTBX0KfMtgtMk10uPU05ihoA?usp=sharing' style='padding-left: 0.5rem;'>
      <img src='https://colab.research.google.com/assets/colab-badge.svg' alt='Google Colab'>
    </a>
