### ISSUE TITLE
Training Dataset Pre-processing process

### ISSUE THREAD

**Issue by xyyeah** [YuliangXiu/ICON#27]
Thanks for the exciting work! Could you please share the training dataset pre-processing process? In addition, how is the model trained?

**Comment by YuliangXiu** [comment]
@xyyeah 
[Dataset processing](https://github.com/YuliangXiu/ICON/blob/master/docs/dataset.md)
[Training](https://github.com/YuliangXiu/ICON/blob/master/docs/training.md)
