### ISSUE TITLE
mv: cannot stat 'smpl_data': No such file or directory

### ISSUE THREAD

**Issue by jacquelinelala** [YuliangXiu/ICON#29]
colab  download problem: mv: cannot stat 'smpl_data': No such file or directory
so during test demo in example there exists bug:
FileNotFoundError: [Errno 2] No such file or directory: '/content/ICON/apps/../lib/dataset/../../data/smpl_related/smpl_data/smplx_faces.npy'

Hi  how to solve it on colab?

**Comment by YuliangXiu** [comment]
I guess you used the wrong username or password for ICON.

**Comment by jacquelinelala** [comment]
> 

Hi! there is another problem: AssertionError: Path /content/ICON/apps/../lib/dataset/../../data/smpl_related/models/smpl does not exist!

**Comment by YuliangXiu** [comment]
Please check the `fetch_data.sh` and [structure of data folder](https://github.com/YuliangXiu/ICON/blob/master/docs/installation.md#tree-structure-of-data-folder)
