### ISSUE TITLE
How to get the parameters of SMPL and the corresponding camera?

### ISSUE THREAD

**Issue by Talegqz** [YuliangXiu/ICON#31]
Thanks for your excellent work! 
The results are very exciting, and I want to use the result of SMPL as prior for other work, but I don't know how to get the parameters of SMPL and the corresponding camera.
Could you tell me how to get it?
Thanks for your help!

**Comment by YuliangXiu** [comment]
SMPL params: you could save `optimized_{orient, pose, betas, trans}` at [here](https://github.com/YuliangXiu/ICON/blob/master/apps/infer.py#L256)

corresponding cameras: [PyTorch3D rendering](https://github.com/YuliangXiu/ICON/blob/1d5a4573138ab6f684bb2fa10c00ee53f1d443c8/lib/common/render.py#L125), [render-to-image alignment](https://github.com/YuliangXiu/ICON/blob/1d5a4573138ab6f684bb2fa10c00ee53f1d443c8/lib/dataset/mesh_util.py#L61)

**Comment by xiegongsheldon** [comment]
> SMPL params: you could save `optimized_{orient, pose, betas, trans}` at [here](https://github.com/YuliangXiu/ICON/blob/master/apps/infer.py#L256)
> 
> corresponding cameras: [PyTorch3D rendering](https://github.com/YuliangXiu/ICON/blob/1d5a4573138ab6f684bb2fa10c00ee53f1d443c8/lib/common/render.py#L125), [render-to-image alignment](https://github.com/YuliangXiu/ICON/blob/1d5a4573138ab6f684bb2fa10c00ee53f1d443c8/lib/dataset/mesh_util.py#L61)

hello i have a question about the shape of optimized_pose. The standard SMPL model takes 72 pose parameters but here the shape is [1, 23, 3, 3 ], how to convert to [1,72] shape?

**Comment by YuliangXiu** [comment]
> > SMPL params: you could save `optimized_{orient, pose, betas, trans}` at [here](https://github.com/YuliangXiu/ICON/blob/master/apps/infer.py#L256)
> > corresponding cameras: [PyTorch3D rendering](https://github.com/YuliangXiu/ICON/blob/1d5a4573138ab6f684bb2fa10c00ee53f1d443c8/lib/common/render.py#L125), [render-to-image alignment](https://github.com/YuliangXiu/ICON/blob/1d5a4573138ab6f684bb2fa10c00ee53f1d443c8/lib/dataset/mesh_util.py#L61)
> 
> hello i have a question about the shape of optimized_pose. The standard SMPL model takes 72 pose parameters but here the shape is [1, 23, 3, 3 ], how to convert to [1,72] shape?

Just check out this issue answer.

[SMPL pose parameters](https://github.com/akashsengupta1997/STRAPS-3DHumanShapePose/issues/12#issuecomment-868983831)

**Comment by zhan-xu** [comment]
Hi @Talegqz were you able to get camera intrinsic and extrinsic matrices? Thank you.

**Comment by xiegongsheldon** [comment]
谢谢！邮件已收到。

**Comment by xiegongsheldon** [comment]
谢谢！邮件已收到。
