### ISSUE TITLE
Error in Colab: FileNotFoundError: [Errno 2] No such file or directory: '/content/ICON/apps/../lib/pymaf/core/../../../data/pymaf_data/pretrained_model/PyMAF_model_checkpoint.pt'

### ISSUE THREAD

**Issue by shuanglinyan** [YuliangXiu/ICON#32]
![图片](https://user-images.githubusercontent.com/67671361/159923869-53238ad2-f2b9-42db-8e4e-873b8d2c822d.png)

**Comment by shuanglinyan** [comment]
I also tried to download the PyMAF_model_checkpoint.pt file via https://drive.google.com/uc?id=1YszE4kE1XPKW9gOua7FaeqWZLawFmVbh and upload it to colab, but the file could not be uploaded

**Comment by YuliangXiu** [comment]
I found that some lower versions of gdown will cause such errors.

So I add `pip install --upgrade gdown` in the `fetch_hps.sh` at [L21](https://github.com/YuliangXiu/ICON/blob/master/fetch_hps.sh#L21)

**Comment by shuanglinyan** [comment]
Thanks!
