### ISSUE TITLE
Bugs when infer on another gpu instead of gpu 0

### ISSUE THREAD

**Issue by hoyeYang** [YuliangXiu/ICON#38]
Thanks for your great work. 
I want to use another gpu to run the demo, so I modify 
https://github.com/YuliangXiu/ICON/blob/53273e081cbc15e3afeba098f067a32cd4db4771/apps/infer.py#L71
to 
```python
   os.environ['CUDA_VISIBLE_DEVICES'] = "0,1,2,3,4,5,6,7"
```
Then I run
```bash
 python infer.py -cfg ../configs/icon-filter.yaml -gpu 1 -in_dir ../examples -out_dir ../results -hps_type pixie
```
But errors occur. 
![1](https://user-images.githubusercontent.com/49240256/162116672-6aee0af6-0f69-4c61-a83d-3eb16acf97dd.PNG)
Then I find out that the implementation of point_to_mesh_distance in kaolin use .cuda() to force tensors on gpu0.  
https://github.com/YuliangXiu/ICON/blob/53273e081cbc15e3afeba098f067a32cd4db4771/lib/dataset/mesh_util.py#L282
So I modify 
https://github.com/NVIDIAGameWorks/kaolin/blob/54d8fa438f8987444637f80da02bb0b862d3694d/kaolin/metrics/trianglemesh.py#L116-L118
to
```python
        min_dist = torch.zeros((num_points), dtype=points.dtype).to(points.device)
        min_dist_idx = torch.zeros((num_points), dtype=torch.long).to(points.device)
        dist_type = torch.zeros((num_points), dtype=torch.int32).to(points.device)
```
and reinstall kaolin from local.
Then I meet one of the following errors. 
![2](https://user-images.githubusercontent.com/49240256/162121048-3eed9f3e-5b10-4a48-b302-905f41b80dcd.PNG)
or
![3](https://user-images.githubusercontent.com/49240256/162122227-fc1c8103-000a-4245-9c38-c1044a876d33.PNG)
Using gpu 2, gpu 3,... will also trigger the error.
Could you help me to solve these errors.

**Comment by YuliangXiu** [comment]
ICON only supports single GPU inference, I recommend using following command without changing the `os.environ` 

```bash
CUDA_VISIBLE_DEVICES=0 python infer.py
```

**Comment by hoyeYang** [comment]
So my question is can we use gpu=1 for inference? current code only trig gpu=0

**Comment by YuliangXiu** [comment]
Have you tried

```
CUDA_VISIBLE_DEVICES=1 python infer.py .....
```

**Comment by hoyeYang** [comment]
Oh, I know how to solve it.
I should comment the line 71 in infer.py, or it will still use gpu0 to compute results.
https://github.com/YuliangXiu/ICON/blob/53273e081cbc15e3afeba098f067a32cd4db4771/apps/infer.py#L71

And then run
```python
CUDA_VISIBLE_DEVICES=1 python infer.py -cfg ../configs/icon-filter.yaml -gpu 0 -in_dir ../examples -out_dir ../results -hps_type pixie
```
Sorry for my carelessness.
Thanks a lot!
