### ISSUE TITLE
add web demo/model to Huggingface

### ISSUE THREAD

**Issue by AK391** [YuliangXiu/ICON#39]
Hi, would you be interested in adding ICON to Hugging Face? The Hub offers free hosting, and it would make your work more accessible and visible to the rest of the ML community. Models/datasets/spaces(web demos) can be added to a user account or organization similar to github.

Example from other organizations:
Keras: https://huggingface.co/keras-io
Microsoft: https://huggingface.co/microsoft
Facebook: https://huggingface.co/facebook

Example spaces with repos:
github: https://github.com/salesforce/BLIP
Spaces: https://huggingface.co/spaces/salesforce/BLIP

github: https://github.com/facebookresearch/omnivore
Spaces: https://huggingface.co/spaces/akhaliq/omnivore

and here are guides for adding spaces/models/datasets to your org

How to add a Space: https://huggingface.co/blog/gradio-spaces
how to add models: https://huggingface.co/docs/hub/adding-a-model
uploading a dataset: https://huggingface.co/docs/datasets/upload_dataset.html

Please let us know if you would be interested and if you have any questions, we can also help with the technical implementation.

**Comment by YuliangXiu** [comment]
Hi @AK391 

Thanks for asking, I am willing to add ICON into **HuggingFace Space**, but I have two questions:

1. SMPL must only be distributed from our site and ICON depends on SMPL.
2. I have prepared a <a href='https://colab.research.google.com/drive/1-AWeWhPvCTBX0KfMtgtMk10uPU05ihoA?usp=sharing' style='padding-left: 0.5rem;'><img src='https://colab.research.google.com/assets/colab-badge.svg' alt='Google Colab'></a>, but the installation contains conda+pip setup, downloading the models from MPI's website with registration.

I didn't have a lot experience in HuggingFace Space (Gradio), maybe you are the perfect person who can answer these qusetions.

**Comment by AK391** [comment]
@YuliangXiu thanks, if I understand correctly the models would need to be private? Could the models be downloaded with a registered user using wget so they are not hosted on huggingface but only downloaded for the demo?

**Comment by YuliangXiu** [comment]
The models can only be downloaded by the people who have registered on our website, so is it easy to add a login module in Gradio? And I am not sure all the required packages can be successfully installed by pip, for now, some from `conda install`, others from `pip install`, see [colab.sh](https://github.com/YuliangXiu/ICON/blob/master/colab.sh)

**Comment by MichaelJBlack** [comment]
The key thing is that people need to obtain SMPL/SMPL-X for research purposes from our website and accept the terms of use. For commercial use, they need to obtain a license from Meshcapade.com.  The license for SMPL does not allow redistribution. So, I assume to run the demo, people will need to have obtained SMPL separately.

**Comment by YuliangXiu** [comment]
HuggingFace Space in [![Hugging Face Spaces](https://img.shields.io/badge/%F0%9F%A4%97%20Hugging%20Face-Spaces-yellow)](https://huggingface.co/spaces/Yuliang/ICON)
