### ISSUE TITLE
Modified smplx or cannot import name 'ModelOutput' from 'smplx.body_models'

### ISSUE THREAD

**Issue by guayabas** [YuliangXiu/ICON#4]
Hi Yuliang,
Thanks for releasing the ICON code and adding instructions for building/testing. 

I am having the issue shown in the attached image. In the instructions it is pointed out to clone smplx from git@github.com:YuliangXiu/smplx.git but that repo does not exist.

The original smplx from https://github.com/vchoutas/smplx does contain a 'ModelOutput' class but not with the properties you are using in your repo/code ergo the error I am getting when testing the ICON example.
![Screenshot from 2022-02-01 17-59-31](https://user-images.githubusercontent.com/1096151/152081900-0d810882-b29e-41dc-b486-241bfdb7901d.png)

**Comment by YuliangXiu** [comment]
Oh, I forgot to change the visibility of `git@github.com:YuliangXiu/smplx.git`. Now you can git clone it.

**Comment by guayabas** [comment]
Awesome, now it is running fine (pifu and pamir examples, icon-filter and icon-nofilter have some issues with bvh_distance_queries but that is irrelevant for this thread). Thanks for the help.

**Comment by YuliangXiu** [comment]
> Awesome, now it is running fine (pifu and pamir examples, icon-filter and icon-nofilter have some issues with bvh_distance_queries but that is irrelevant for this thread). Thanks for the help.

Please check #5

**Comment by YuliangXiu** [comment]
@guayabas I have replaced the `bvh-distance-queries` with `PyTorch3D+Kaolin`, thus you don't need to install it anymore.
