### ISSUE TITLE
Will VIBE be supported as optional HPS?

### ISSUE THREAD

**Issue by DingYikang** [YuliangXiu/ICON#45]
Thanks for your wonderful work! I'm wondering will you support VIBE as optional HPS?  I found that VIBE performs more robust than PyMAF, etc in challenging videos, so I'm wondering if you have tested VIBE and will VIBE be supported?
Thanks and looking forward to your reply!

**Comment by YuliangXiu** [comment]
I didn't test VIBE. But if you want to merge VIBE into ICON, pull request is welcome.

Please check [TestDataset](https://github.com/YuliangXiu/ICON/blob/master/lib/dataset/TestDataset.py#L104) for reference.

**Comment by YuliangXiu** [comment]
Hi @DingYikang, now PIXIE, PARE, PyMAF, HybrIK, BEV are all supported in ICON.
