### ISSUE TITLE
colab running error

### ISSUE THREAD

**Issue by Kxitinga** [YuliangXiu/ICON#46]
There is something error when i running in the colab,I want to ask you for some help.here is the error， Thank you for your help.

error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for voxelize-cuda (setup.py) ... error
  ERROR: Failed building wheel for voxelize-cuda
  Running setup.py clean for voxelize-cuda
  Building wheel for kaolin (setup.py) ... done
  Created wheel for kaolin: filename=kaolin-0.10.0-cp38-cp38-linux_x86_64.whl size=984560 sha256=534cd6e51cca93946d4ed5248b12077374eb8a96c0d3d9a2a2c546598b019d8d
  Stored in directory: /tmp/pip-ephem-wheel-cache-owjr1c2q/wheels/b0/0c/b7/c21c4d2eb6360afe4d8728dfb21dbf88790f99fefa0885a0b5
Successfully built human-det smplx pytorch3d kaolin
Failed to build voxelize-cuda
Installing collected packages: voxelize-cuda, usd-core, kaolin
  error: subprocess-exited-with-error
  
  × Running setup.py install for voxelize-cuda did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Running setup.py install for voxelize-cuda ... error
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> voxelize-cuda

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by YuliangXiu** [comment]
If you won't run PaMIR, you can comment out all the `voxelize-cuda` codes.
