### ISSUE TITLE
Textured clothed model from multiple-view

### ISSUE THREAD

**Issue by ujjawalcse** [YuliangXiu/ICON#48]
Hey,
Congrats for the great work.
I successfully ran this repository and getting the results from the visible view. Now, I want to extend it to a full clothed textured human body model using multiple view (like front, back ,left and right).

Any plan to do this task?
Can you suggest some ideas how to do the same ?

**Comment by YuliangXiu** [comment]
#33

**Comment by YuliangXiu** [comment]
@ujjawalcse 

ECON now supports full texture generation w/ the help of TEXTure

https://github.com/YuliangXiu/ECON#texture

[1] Richardson E, Metzer G, Alaluf Y, et al. Texture: Text-guided texturing of 3d shapes[J]. arXiv preprint arXiv:2302.01721, 2023.

**Comment by YuliangXiu** [comment]
We recently released a new work, TeCH. Given a single image, TeCH could produce a **full textured avatar** with both intricate geometric details and consistent high-quality texture.

<div align="center">
    <video autoplay loop muted src="https://github.com/huangyangyi/TeCH/assets/7944350/f8fc55ed-9cbe-4b5f-bd1d-237396360713" type=video/mp4>
    </video>
  </div>

Homepage: https://huangyangyi.github.io/TeCH/

**Comment by ujjawalcse** [comment]
Thanks, @YuliangXiu for the notification. Kudos !!
