### ISSUE TITLE
Texture of human model

### ISSUE THREAD

**Issue by MorganPhobo5** [YuliangXiu/ICON#49]
Hello. Thank you for your awesome work and providing source code. 
But i have question: Is there any possible ways to extract texture from image?

**Comment by YuliangXiu** [comment]
The final [_refine.obj](https://github.com/YuliangXiu/ICON/blob/master/apps/infer.py#L457) already contains the half-texture projected from the original image. But ICON doesn't support full-texture extraction (from multi-view inputs) or prediction(like PIFu) for now.

**Comment by YuliangXiu** [comment]
@MorganPhobo5 

ECON now supports full texture generation w/ the help of TEXTure

https://github.com/YuliangXiu/ECON#texture

[1] Richardson E, Metzer G, Alaluf Y, et al. Texture: Text-guided texturing of 3d shapes[J]. arXiv preprint arXiv:2302.01721, 2023.

**Comment by YuliangXiu** [comment]
@MorganPhobo5 We recently released a new work, TeCH. Given a single image, TeCH could produce a **full textured avatar** with both intricate geometric details and consistent high-quality texture.

<div align="center">
    <video autoplay loop muted src="https://github.com/huangyangyi/TeCH/assets/7944350/f8fc55ed-9cbe-4b5f-bd1d-237396360713" type=video/mp4>
    </video>
  </div>

Homepage: https://huangyangyi.github.io/TeCH/

**Comment by teamcoltra** [comment]
> @MorganPhobo5 We recently released a new work, TeCH. Given a single image, TeCH could produce a **full textured avatar** with both intricate geometric details and consistent high-quality texture.
> 
>  teaser.mp4 
> Homepage: https://huangyangyi.github.io/TeCH/

I stumbled into this earlier today and now see this comment, I'm really excited for you guys to release the github for this.
