### ISSUE TITLE
Colab installation error 

### ISSUE THREAD

**Issue by Sunil7545** [YuliangXiu/ICON#51]
Dear Yuliang Xiu,

during the package installation on colab page, I am getting the following error:

ERROR: pip's legacy dependency resolver does not consider dependency conflicts when selecting packages. This behaviour is the source of the following dependency conflicts.
kornia 0.4.0 requires torch<1.7.0,>=1.6.0, but you'll have torch 1.8.2 which is incompatible.
rembg 2.0.13 requires pillow==9.0.1, but you'll have pillow 9.0.0 which is incompatible.
rembg 2.0.13 requires scipy==1.7.3, but you'll have scipy 1.5.2 which is incompatible.

and when running on the test data

Traceback (most recent call last):
  File "infer.py", line 96, in <module>
    dataset = TestDataset(dataset_param, device)
  File "/content/ICON/apps/../lib/dataset/TestDataset.py", line 94, in __init__
    self.smpl_model = self.get_smpl_model(self.smpl_type, self.smpl_gender).to(self.device)
  File "/content/ICON/apps/../lib/dataset/TestDataset.py", line 87, in <lambda>
    self.get_smpl_model = lambda smpl_type, smpl_gender : smplx.create(
  File "/usr/local/envs/icon/lib/python3.8/site-packages/smplx/body_models.py", line 2413, in create
    return SMPL(model_path, **kwargs)
  File "/usr/local/envs/icon/lib/python3.8/site-packages/smplx/body_models.py", line 145, in __init__
    assert osp.exists(smpl_path), 'Path {} does not exist!'.format(
AssertionError: Path /content/ICON/apps/../lib/dataset/../../data/smpl_related/models/smpl does not exist!

Please take a look

Thanks 
Sunil

**Comment by bykof** [comment]
You have to run the 
```
# download models and extra data (register required)
# skip download of "training", "pare", "pixie" if you don't need them

%cd /content/ICON
!bash fetch_data.sh # input "N" to avoid downloading data used for training
!bash fetch_hps.sh # input "N" to avoid downloading PARE
```
again and press yes if the program asks to download the models for training. (actually press always yes)

**Comment by PrateekPal641** [comment]
Getting the same error even after running this block
