### ISSUE TITLE
Question regarding predicted normal

### ISSUE THREAD

**Issue by NIRVANALAN** [YuliangXiu/ICON#54]
Hi Yuliang, thanks for your contribution to the community, I have a few questions here.

1. Here you predict sdf and a pix2pix normal, since for sdf the normal is the gradient of the output points to the sdf prediction, I wonder will the final geometry reconstructed conflicts with the normal you predicted with pix2pix model?
2. To train the geometry reconstruction part, you need to randomly sample points in the 3D space and calculate the loss, what sampling strategy you adopted here, similar to pifu model?
3. You supervise the IF model with ground-truth occupancy o(P) and use 0.5 as the iso-surface, I wonder why don't you directly use the ground-truth sdf value from render people and learn an 0 iso-surface directly?
4. Here you use mse to supervise the geometry prediction, I have saw some other choices like bce loss to supervise the in/out of predicted points, do you have suggestions over which supervision is better to use ?

Thanks.

**Comment by YuliangXiu** [comment]
Good questions:
1. Yes. If you check the output results (.png), it's obvious that the normal image rendered from reconstruction is somehow different from the pix2pix predicted normal image. Basically, the pix2pix normal images always have better quality in details.
2. Yes, similar to PIFu model.
3. Yes, SDF works as well, but cannot make a big difference, so we still follow the original scheme.
4. Same as SDF vs Occupancy, it works but makes no difference both qualitatively or qualitatively.
