### ISSUE TITLE
UnZip file errors 

### ISSUE THREAD

**Issue by 3vaD3** [YuliangXiu/ICON#55]
Archive:  icon_data.zip
  End-of-central-directory signature not found.  Either this file is not a zipfile, or it constitutes one disk of a multi-part archive.  In the  latter case the central directory and zipfile comment will be found on the last disk(s) of this archive.

-The same error applies to SMPL and mpips zip files

-I have tried unzipping / viewing zip files  manually/offline.
 
-Windows doesn't  recognise the file content as a "zipped file"

-I have registered with all nessesary sites and all logins appears valid... ie no errors are shown.

Can u validate the zip files and links are okay?

In not sure what the issue might be.

**Comment by YuliangXiu** [comment]
I tried to download these zip files on my Chrome and Terminal(with `wget`), and both work well.

Maybe you can also try to get them from ICON's webpage, https://icon.is.tue.mpg.de/download.php
