### ISSUE TITLE
smpl parameters question

### ISSUE THREAD

**Issue by xiegongsheldon** [YuliangXiu/ICON#56]
hello i have a question about the shape of optimized_pose. The standard SMPL model takes 72 pose parameters but here the shape is [1, 23, 3, 3 ], how to convert to [1,72] shape?

**Comment by YuliangXiu** [comment]
Just check out this issue answer.

[SMPL pose parameters](https://github.com/akashsengupta1997/STRAPS-3DHumanShapePose/issues/12#issuecomment-868983831)

**Comment by xiegongsheldon** [comment]
> Just check out this issue answer.
> 
> [SMPL pose parameters](https://github.com/akashsengupta1997/STRAPS-3DHumanShapePose/issues/12#issuecomment-868983831)

![Screenshot from 2022-05-17 13-59-45](https://user-images.githubusercontent.com/57121627/168740327-f8db9c5b-c088-45f9-b4dd-8417795501bf.png)
that is what i did, is it right?

**Comment by xiegongsheldon** [comment]
my results show it is wrong, could you give some suggestions thank you very much 
![Screenshot from 2022-05-17 14-10-32](https://user-images.githubusercontent.com/57121627/168741199-e9b199e0-0756-4f55-a853-cd44ad5a6b96.png)
