### ISSUE TITLE
can this be setup on google colab?

### ISSUE THREAD

**Issue by GeorvityLabs** [YuliangXiu/ICON#6]
really awesome project.
Would be great to have a user input and run inference to get result on google colab!

hope you guys can set this project up there.

**Comment by YuliangXiu** [comment]
Thanks for your suggestions, I am working on it and will let you know once finished.

**Comment by GeorvityLabs** [comment]
cool , looking forward to it.

**Comment by YuliangXiu** [comment]
@GeorvityLabs 

<a href="https://colab.research.google.com/drive/1-AWeWhPvCTBX0KfMtgtMk10uPU05ihoA?usp=sharing" style="padding-left: 0.5rem;"> <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Google Colab" /> </a>
