### ISSUE TITLE
OpenGL.raw.EGL._errors.EGLError: EGLError( )

### ISSUE THREAD

**Issue by Yuhuoo** [YuliangXiu/ICON#60]
When I run the command of "bash render_batch.sh debug", it gives an error as following

OpenGL.raw.EGL._errors.EGLError: EGLError(
        err = EGL_NOT_INITIALIZED,
        baseOperation = eglInitialize,
        cArguments = (
                <OpenGL._opaque.EGLDisplay_pointer object at 0x7f7b3d0ee2c0>,
                <importlib._bootstrap.LP_c_int object at 0x7f7b3d0ee440>,
                <importlib._bootstrap.LP_c_int object at 0x7f7b3d106bc0>,
        ),
        result = 0
)

How can I fix this?

**Comment by YuliangXiu** [comment]
I updated the [dataset.md](https://github.com/YuliangXiu/ICON/blob/master/docs/dataset.md), the correct command should be `bash render_batch.sh debug all`.

**Comment by Yuhuoo** [comment]
> I updated the [dataset.md](https://github.com/YuliangXiu/ICON/blob/master/docs/dataset.md), the correct command should be `bash render_batch.sh debug all`.

Much thanks for your reply. But it doesn't work for me...

**Comment by YuliangXiu** [comment]
According to the error log, it seems that you didn't install EGL, please follow the [dataset.md (Environement)](https://github.com/YuliangXiu/ICON/blob/master/docs/dataset.md#environment) to install all the required packages.

**Comment by Yuhuoo** [comment]
> According to the error log, it seems that you didn't install EGL, please follow the [dataset.md (Environement)](https://github.com/YuliangXiu/ICON/blob/master/docs/dataset.md#environment) to install all the required packages.

Thanks again for your reply!! But I think I have installed EGL. The info as follows.

(ICON) root@Ib5b57dff600a01084:/hy-tmp# sudo apt-get install freeglut3-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
freeglut3-dev is already the newest version (2.8.1-3).
0 upgraded, 0 newly installed, 0 to remove and 70 not upgraded.
(ICON) root@Ib5b57dff600a01084:/hy-tmp# apt install libgl1-mesa-dri libegl1-mesa libgbm1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libgbm1 is already the newest version (21.2.6-0ubuntu0.1~20.04.2).
libgl1-mesa-dri is already the newest version (21.2.6-0ubuntu0.1~20.04.2).
libegl1-mesa is already the newest version (21.2.6-0ubuntu0.1~20.04.2).
0 upgraded, 0 newly installed, 0 to remove and 70 not upgraded.

I have no idea to fix this...5555

**Comment by Yuhuoo** [comment]
> According to the error log, it seems that you didn't install EGL, please follow the [dataset.md (Environement)](https://github.com/YuliangXiu/ICON/blob/master/docs/dataset.md#environment) to install all the required packages.

Thanks again for your reply!! But I think I have installed EGL. The info as follows.

(ICON) root@Ib5b57dff600a01084:/hy-tmp# sudo apt-get install freeglut3-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
freeglut3-dev is already the newest version (2.8.1-3).
0 upgraded, 0 newly installed, 0 to remove and 70 not upgraded.
(ICON) root@Ib5b57dff600a01084:/hy-tmp# apt install libgl1-mesa-dri libegl1-mesa libgbm1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libgbm1 is already the newest version (21.2.6-0ubuntu0.1~20.04.2).
libgl1-mesa-dri is already the newest version (21.2.6-0ubuntu0.1~20.04.2).
libegl1-mesa is already the newest version (21.2.6-0ubuntu0.1~20.04.2).
0 upgraded, 0 newly installed, 0 to remove and 70 not upgraded.

I have no idea to fix this...5555

**Comment by Yuhuoo** [comment]
> According to the error log, it seems that you didn't install EGL, please follow the [dataset.md (Environement)](https://github.com/YuliangXiu/ICON/blob/master/docs/dataset.md#environment) to install all the required packages.

I followed the latest [dataset.md (Environement)] (https://github.com/YuliangXiu/ICON/blob/master/docs/dataset.md#environment) using " set egl=False and unset PYOPENGL_PLATFORM "，but I still got an error about " freeglut (foo): failed to open display '' "

**Comment by Yuhuoo** [comment]
> According to the error log, it seems that you didn't install EGL, please follow the [dataset.md (Environement)](https://github.com/YuliangXiu/ICON/blob/master/docs/dataset.md#environment) to install all the required packages.



I followed the latest  [dataset.md (Environement)](https://github.com/YuliangXiu/ICON/blob/master/docs/dataset.md#environment) using " set egl=False and unset PYOPENGL_PLATFORM "，but I still got an error about " freeglut (foo): failed to open display '' "

**Comment by Yuhuoo** [comment]
> `freeglut (foo)` error often means the program cannot find the screen or you are using clusters without displayer. In such cases, we recommend to use EGL headless mode for rendering. As for the TBB error, never saw this before, don't forget to write down your solution once solved.

OK！I will do that when I solved the TBB error. But I still annoyed by the opengl error. I gave up the EGL headless mode, and I used the X11 forwarding to run the script " bash render_batch.sh debug all ", but I still got an error as follows.

OpenGL.error.GLError: GLError(
        err = 1282,
        description = b'invalid operation',
        baseOperation = glTexImage2DMultisample,
        cArguments = (
                GL_TEXTURE_2D_MULTISAMPLE,
                16,
                GL_RGBA32F,
                512,
                512,
                GL_TRUE,
        )
)

**Comment by LT-321** [comment]
> 当我运行“bash render_batch.sh debug”命令时，出现如下错误
> 
> OpenGL.raw.EGL._errors.EGLError: EGLError( err = EGL_NOT_INITIALIZED, baseOperation = eglInitialize, cArguments = ( <OpenGL._opaque.EGLDisplay_pointer object at 0x7f7b3d0ee2c0>, <importlib._bootstrap.LP_c_int object at 0x7f7b3d0ee440>, <importlib._bootstrap. LP_c_int 对象位于 0x7f7b3d106bc0>, ), result = 0 )
> 
> 我怎样才能解决这个问题？

I also encountered the same problem! Whether it's "headless rendering" or not, our mistakes are very similar. That's strange

> When I run the command of "bash render_batch.sh debug", it gives an error as following
> 
> OpenGL.raw.EGL._errors.EGLError: EGLError( err = EGL_NOT_INITIALIZED, baseOperation = eglInitialize, cArguments = ( <OpenGL._opaque.EGLDisplay_pointer object at 0x7f7b3d0ee2c0>, <importlib._bootstrap.LP_c_int object at 0x7f7b3d0ee440>, <importlib._bootstrap.LP_c_int object at 0x7f7b3d106bc0>, ), result = 0 )
> 
> How can I fix this?

I also encountered the same problem! Whether it's "headless rendering" or not, our mistakes are very similar. That's strange

**Comment by LT-321** [comment]
> When I run the command of "bash render_batch.sh debug", it gives an error as following
> 
> OpenGL.raw.EGL._errors.EGLError: EGLError( err = EGL_NOT_INITIALIZED, baseOperation = eglInitialize, cArguments = ( <OpenGL._opaque.EGLDisplay_pointer object at 0x7f7b3d0ee2c0>, <importlib._bootstrap.LP_c_int object at 0x7f7b3d0ee440>, <importlib._bootstrap.LP_c_int object at 0x7f7b3d106bc0>, ), result = 0 )
> 
> How can I fix this?

I also encountered the same problem! Whether it's "headless rendering" or not, our mistakes are very similar. That's strange

**Comment by Yuhuoo** [comment]
Oh! Yeah! I think I have solved the problem. The Steps as follows.
1、export PYOPENGL_PLATFORM=egl
2、export MESA_GL_VERSION_OVERRIDE=3.3
3、Change the ms_rate=16 to ms_rate=1.0 in line 115 of render_single.py

But what does the param "ms_rate" mean? If I change the param, will I get the wrong result?

**Comment by YuliangXiu** [comment]
Higher ms_rate is used for Anti-aliasing [1], please look at the face boundary.

|![image](https://user-images.githubusercontent.com/7944350/169666552-bb4fee1c-a4d7-4398-a2a1-0a525d3ed0b4.png)|![image](https://user-images.githubusercontent.com/7944350/169666639-9782402a-0b09-4bc3-bf33-dee3b1c6808f.png)|![image](https://user-images.githubusercontent.com/7944350/169666603-718da597-f3d6-45b6-8bba-426b40b11a51.png)|
|:---:|:---:|:---:|
|ms_rate=1|ms_rate=16|ms_rate=64|

If you change this param, you will get less realistic rendering results, which will harm the trained model. BTW, my `PyOpenGL == 3.1.1a1`, maybe you could also try the rendering scripts on others' machines.

[1] https://learnopengl.com/Advanced-OpenGL/Anti-Aliasing

**Comment by Yuhuoo** [comment]
> Higher ms_rate is used for Anti-aliasing [1], please look at the face boundary.
> 
> ![image](https://user-images.githubusercontent.com/7944350/169666552-bb4fee1c-a4d7-4398-a2a1-0a525d3ed0b4.png)	![image](https://user-images.githubusercontent.com/7944350/169666639-9782402a-0b09-4bc3-bf33-dee3b1c6808f.png)	![image](https://user-images.githubusercontent.com/7944350/169666603-718da597-f3d6-45b6-8bba-426b40b11a51.png)
> ms_rate=1	ms_rate=16	ms_rate=64
> If you change this param, you will get less realistic rendering results, which will harm the trained model. BTW, my `PyOpenGL == 3.1.1a1`, maybe you could also try the rendering scripts on others' machines.
> 
> [1] https://learnopengl.com/Advanced-OpenGL/Anti-Aliasing

OK! Much thanks for your reply! I checked the GPU on my machine is Tesla V100-SXM2-16GB, and I checked the parameter GL_MAX_SAMPLES is 4, maybe that's why I can't use the ms_rate=16 . Could you tell me which GPU you are using?

**Comment by Yuhuoo** [comment]
OK! Much thanks for your reply! I checked the GPU on my machine is Tesla V100-SXM2-16GB, and I checked the parameter GL_MAX_SAMPLES is 4, maybe that's why I can't use the ms_rate=16 . Could you tell me which GPU you are using?

**Comment by YuliangXiu** [comment]
I am using `Quadro RTX 5000`. I don't think ms_rate=4 will affect the final performance a lot.

**Comment by Yuhuoo** [comment]
> 

TBB error and OMP Info may be just warning refrencing from 
https://github.com/numba/numba/issues/6350#issuecomment-724671971
https://github.com/numba/numba/issues/5275#issuecomment-1012702294

Solutions:
Suppressing the TBB error warnings by using NUMBA_THREADING_LAYER='omp' python <my program>
Suppressing the OMP Info warnings by using os.environ['KMP_WARNINGS'] = 'off' after import os

**Comment by mmmcn** [comment]
@Yuhuoo Hi, now can you run `bash render_batch.sh debug` normally? I still got an error after running `bash reneder_batch.sh debug `:  
```shell
-> rndr = PRTRender(width=size, height=size, ms_rate=16, egl=egl)
(Pdb) c
Traceback (most recent call last):
  File "./render_single.py", line 125, in <module>
    rndr = PRTRender(width=size, height=size, ms_rate=16, egl=egl)
  File "/home/private/project/3d-holographic-reconstruction/ICON/scripts/./../lib/renderer/gl/prt_render.py", line 35, in __init__
    CamRender.__init__(self,
  File "/home/private/project/3d-holographic-reconstruction/ICON/scripts/./../lib/renderer/gl/cam_render.py", line 32, in __init__
    Render.__init__(self,
  File "/home/private/project/3d-holographic-reconstruction/ICON/scripts/./../lib/renderer/gl/render.py", line 96, in __init__
    glTexImage2DMultisample(GL_TEXTURE_2D_MULTISAMPLE,
  File "/home/private/Software/anaconda3/envs/icon/lib/python3.8/site-packages/OpenGL/platform/baseplatform.py", line 415, in __call__
    return self( *args, **named )
  File "src/errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.error.GLError: GLError(
	err = 1282,
	description = b'invalid operation',
	baseOperation = glTexImage2DMultisample,
	cArguments = (
		GL_TEXTURE_2D_MULTISAMPLE,
		16,
		GL_RGBA32F,
		512,
		512,
		GL_TRUE,
	)
)
```
I am not sure if it's the packages' version in python env leads to this, can you share the version of the packages you use?

**Comment by Yuhuoo** [comment]
> 

You can use ms_rate=4 in line 115 of render_single.py to fix this.

**Comment by lyk412** [comment]
When I run `bash scripts/render_batch.sh debug all`, I encountered the problem!
How can I solve it? 

Traceback (most recent call last):
  File "scripts/render_single.py", line 37, in <module>
    initialize_GL_context(width=size, height=size, egl=egl)
  File "/home/human/lyk/ICON/lib/renderer/gl/init_gl.py", line 23, in initialize_GL_context
    create_opengl_context((width, height))
  File "/home/human/lyk/ICON/lib/renderer/gl/glcontext.py", line 92, in create_opengl_context
    egl.eglInitialize(egl_display, pointer(major), pointer(minor))
  File "/home/human/anaconda3/envs/icon/lib/python3.8/site-packages/OpenGL/platform/baseplatform.py", line 402, in __call__
    return self( *args, **named )
  File "src/errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.error.GLError: GLError(
        err = 12289,
        baseOperation = eglInitialize,
        cArguments = (
                <OpenGL._opaque.EGLDisplay_pointer object at 0x7fd71cf55bc0>,
                <importlib._bootstrap.LP_c_int object at 0x7fd71cf751c0>,
                <importlib._bootstrap.LP_c_int object at 0x7fd71cf75040>,
        ),
        result = 0
)

I try
1、export PYOPENGL_PLATFORM=egl
2、export MESA_GL_VERSION_OVERRIDE=3.3
3、Change the ms_rate=16 to ms_rate=1.0 in line 115 of render_single.py
But it doesn't work.

**Comment by glorioushonor** [comment]
> OK! Much thanks for your reply! I checked the GPU on my machine is Tesla V100-SXM2-16GB, and I checked the parameter GL_MAX_SAMPLES is 4, maybe that's why I can't use the ms_rate=16 . Could you tell me which GPU you are using?

I'm sorry to bother you. I would like to know how to check the parameter GL_MAX_SAMPLES. I tried the code as folows：
```
import OpenGL.GL as gl
gl_max_samples = gl.glGetIntegerv(gl.GL_MAX_SAMPLES)
print("GL_MAX_SAMPLES =", gl_max_samples)
```
I get GL_MAX_SAMPLES=0, but when I set the ms_rate=1, the code works. So I wonder if there's something wrong with the way I get the parameters GL_MAX_SAMPLES.

**Comment by MalignusCN** [comment]
> Oh! Yeah! I think I have solved the problem. The steps as follows. 1、export PYOPENGL_PLATFORM=egl 2、export MESA_GL_VERSION_OVERRIDE=3.3 3、Change the ms_rate=16 to ms_rate=1.0 in line 115 of render_single.py
> 
> But what does the param "ms_rate" mean? If I change the param, will I get the wrong result?



> When I run the command of "bash render_batch.sh debug", it gives an error as following
> 
> OpenGL.raw.EGL._errors.EGLError: EGLError( err = EGL_NOT_INITIALIZED, baseOperation = eglInitialize, cArguments = ( <OpenGL._opaque.EGLDisplay_pointer object at 0x7f7b3d0ee2c0>, <importlib._bootstrap.LP_c_int object at 0x7f7b3d0ee440>, <importlib._bootstrap.LP_c_int object at 0x7f7b3d106bc0>, ), result = 0 )
> 
> How can I fix this?

I fix the bug by replace the code from
`egl_display = egl.eglGetDisplay(egl.EGL_DEFAULT_DISPLAY)`
to 
`egl_display = create_initialized_headless_egl_display()
def create_initialized_headless_egl_display():
  """
  
    Creates an initialized EGL display directly on a device.
    The resolution is from https://github.com/shunsukesaito/PIFu/issues/49
    
  """
  for device in egl_get_devices():
    display = egl.eglGetPlatformDisplayEXT(EGL_PLATFORM_DEVICE_EXT, device, None)

    if display != egl.EGL_NO_DISPLAY and egl.eglGetError() == egl.EGL_SUCCESS:
      # `eglInitialize` may or may not raise an exception on failure depending
      # on how PyOpenGL is configured. We therefore catch a `GLError` and also
      # manually check the output of `eglGetError()` here.
      try:
        initialized = egl.eglInitialize(display, None, None)
      except error.GLError:
        pass
      else:
        if initialized == egl.EGL_TRUE and egl.eglGetError() == egl.EGL_SUCCESS:
          return display
  return egl.EGL_NO_DISPLAY
`
as this mentioned https://github.com/shunsukesaito/PIFu/issues/49#issue-656865184 , hope it can help someone

**Comment by Dragon2938734** [comment]
sorry , i meet the following problem

multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x7f42f7ad3790>'. Reason: 'ValueError('ctypes objects containing pointers cannot be pickled')'

and follow the historic issues, i reach here ,but i cannot find the "render_batch.sh"

**Comment by LarsPh** [comment]
> > Oh! Yeah! I think I have solved the problem. The steps as follows. 1、export PYOPENGL_PLATFORM=egl 2、export MESA_GL_VERSION_OVERRIDE=3.3 3、Change the ms_rate=16 to ms_rate=1.0 in line 115 of render_single.py
> > But what does the param "ms_rate" mean? If I change the param, will I get the wrong result?
> 
> > When I run the command of "bash render_batch.sh debug", it gives an error as following
> > OpenGL.raw.EGL._errors.EGLError: EGLError( err = EGL_NOT_INITIALIZED, baseOperation = eglInitialize, cArguments = ( <OpenGL._opaque.EGLDisplay_pointer object at 0x7f7b3d0ee2c0>, <importlib._bootstrap.LP_c_int object at 0x7f7b3d0ee440>, <importlib._bootstrap.LP_c_int object at 0x7f7b3d106bc0>, ), result = 0 )
> > How can I fix this?
> 
> I fix the bug by replace the code from `egl_display = egl.eglGetDisplay(egl.EGL_DEFAULT_DISPLAY)` to `egl_display = create_initialized_headless_egl_display()` The methods is given in link: [shunsukesaito/PIFu#49 (comment)](https://github.com/shunsukesaito/PIFu/issues/49#issue-656865184) , hope it can help someone

This solved the promblem (OpenGL.raw.EGL._errors.EGLError: EGLError( err = EGL_NOT_INITIALIZED...) in my case.
