### ISSUE TITLE
Could you share your CUDA version and cudnn version?

### ISSUE THREAD

**Issue by Yuhuoo** [YuliangXiu/ICON#61]
The question as shown above, much thanks!

**Comment by YuliangXiu** [comment]
GPU: Quadro RTX 5000
Ubuntu: 20.04

CUDA==11.0
CUDNN==8.0.2

**Comment by YuliangXiu** [comment]
But I don't think these versions need to be strictly the same, lots of users could run ICON under CUDA>11.0 with an unknown cudnn.
