### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Yuhuoo** [YuliangXiu/ICON#63]
When I run the "CUDA_VISIBLE_DEVICES=0 python train.py -cfg ../configs/train/icon-filter.yaml" after the data ready, I have got the error  of " Segmentation fault (core dumped) "
Then I tried to reboot the machine, but it didn't work, and the error still exists.

**Comment by Yuhuoo** [comment]
Dear Yuliang Xiu,
I found possible probelms in importing PARE by printing,  like this
print("-------")
from ..models import PARE
print("-------")
from ..utils.train_utils import load_pretrained_model
print("-------")

and the output is:

-------
Segmentation fault (core dumped)

so, may be the error occurred when importing PARE package. How can I fix this?

**Comment by YuliangXiu** [comment]
You can comment this line if you didn't PARE as your HPS.

**Comment by Yuhuoo** [comment]
Thanks for your reply! But I also met another problem, a red message was printed out on the console:
Use SMPL-X: /hy-tmp/ICON/apps/../lib/dataset/../../data/smpl_related/models/smplx/SMPLX_MALE.npz
Is that normal?

**Comment by YuliangXiu** [comment]
If you are training ICON on THuman2.0, you must download SMPL-X.

Please check [fetch_data.sh](https://github.com/YuliangXiu/ICON/blob/master/fetch_data.sh#L40)
