### ISSUE TITLE
Colab Running Error

### ISSUE THREAD

**Issue by 3DebbieChen9** [YuliangXiu/ICON#64]
Hi there,
While I was running the provided Colab, I have encountered following error.

- After the package installation, I faced the  `dependency conflicts` error
<img width="1579" alt="image" src="https://user-images.githubusercontent.com/58079945/170464947-057151aa-0cf5-4f49-b936-a2c82fe7ee86.png">

- While I was trying to the cell to test on the example, I faced the `TypeError: Descriptors cannot not be created directly.`

<img width="1326" alt="image" src="https://user-images.githubusercontent.com/58079945/170464818-b62d1304-d142-4b26-83c9-4ed0d784765f.png">
<img width="1083" alt="image" src="https://user-images.githubusercontent.com/58079945/170464244-c6e9bfe5-8545-4d0b-9356-116ecf52735a.png">

I run every cell in the Colab, don't know where it gone wrong....

**Comment by 3DebbieChen9** [comment]
I just downgrade the `protobuf` package to 3.20.x, then it could work just fine.

**Comment by YuliangXiu** [comment]
I have updated the `requirements.txt` and Google Colab, everything works well for now.

**Comment by dyy0205** [comment]
> I just downgrade the `protobuf` package to 3.20.x, then it could work just fine.

hi, what's your tensorboard version? when i install the lasted tensorboard==2.10.0, it requires protobuf<3.20,>=3.9.2
