### ISSUE TITLE
How to obtain the centimeter unit？

### ISSUE THREAD

**Issue by sunjc0306** [YuliangXiu/ICON#66]
Hello!
Excuse me again!
I would like to  know what is the basis for the unit of centermeter in the paper.
As far as I know, since each dataset has different units in their model coordinate system, they need to be normalized to a reference space （eg:[-0.5,-0.5,-0.5]*[0.5,0.5,0.5]）when rendering.
The normalized model does not have units, and the height of each human is unknown, so how is the unit of centimeters obtained?
Thanks!

**Comment by YuliangXiu** [comment]
```
types: ["3dpeople","axyz","renderpeople","renderpeople_p27","humanalloy","thuman","cape"]
scales: [1.0, 100.0, 1.0, 1.0, 2.54000508001016, 100.0, 100.0]
```
Here are the `scales` for different datasets, all the raw scans will be re-scaled in **cm** unit.
