### ISSUE TITLE
obj文件绑定骨骼

### ISSUE THREAD

**Issue by zaf05** [YuliangXiu/ICON#67]
你好，我用得到的obj文件，在unity里面打开，却发现没有绑定骨骼，但是看你之前在机器之心公开课时候说有相关权重，请问怎么操作，谢谢？
![image](https://user-images.githubusercontent.com/9206892/171369713-25d7eef7-875f-454e-9346-149d5324d204.png)

**Comment by YuliangXiu** [comment]
那个结果是通过SCANimate训出来的，不过你也可以直接用SMPL的骨骼和蒙皮权重，最后衣服几何细节的动态效果会稍微差一点，但也是可以用的。

**Comment by zaf05** [comment]
是XXX_smpl.obj吗？如果这个的话，我在blender或者unity里面，没看到绑定的骨骼

**Comment by YuliangXiu** [comment]
目前ICON不支持FBX格式文件的导出，另外，关于SMPL模型，请参考[smpl-made-simple](https://smpl-made-simple.is.tue.mpg.de/)
