### ISSUE TITLE
为啥么笔直的正面照片，结果会出现屈膝的结果现象？

### ISSUE THREAD

**Issue by xiegongsheldon** [YuliangXiu/ICON#68]
![test](https://user-images.githubusercontent.com/57121627/171530330-10a92f22-e396-4162-abd9-d027b3a5ca9f.jpg)
![Screenshot from 2022-06-02 09-52-31](https://user-images.githubusercontent.com/57121627/171530367-bc2e3b45-0b01-4d9c-a6d5-7dd129f21435.png)

**Comment by MichaelJBlack** [comment]
Also, most existing human pose estimators have some bias towards a mean pose, which has the legs bent.  This is a common issue.

**Comment by YuliangXiu** [comment]
@MichaelJBlack @xiegongsheldon 

The issue of bending legs get resolved finally, please check out [tricks.md/bending-legs](https://github.com/YuliangXiu/ECON/blob/master/docs/tricks.md#bending-legs).

**Comment by xiegongsheldon** [comment]
谢谢！邮件已收到。
