### ISSUE TITLE
cudaErrorInvalidDevice

### ISSUE THREAD

**Issue by KernelA** [YuliangXiu/ICON#7]
An issue, occurred in the:

https://github.com/YuliangXiu/bvh-distance-queries/blob/49de18e4f0cc0aa8ae7522f33081ae1b73d1bbb0/bvh_distance_queries/bvh_search_tree.py#L42

I run the inference script inside docker container with nvidia-docker on the A100. Driver Version: 510.47.03

Logs from container:
https://gist.github.com/KernelA/2ea3def5846c7f688ce3876f07527768

Installed dependencies:
https://gist.github.com/KernelA/7173fcff115103bc94514a72798f7853

Info about environment:
https://gist.github.com/KernelA/dfdbf7c61e61455d0bf46c8cc21aadfa

Git commit hash: `d1908ce65762a08e4f2723585e485969beae9aa1`

**Comment by YuliangXiu** [comment]
@KernelA 

I just update the [colab.sh](https://github.com/YuliangXiu/ICON/blob/master/colab.sh#L3), you need to change the cuda version from 11.1 to 11.0.

BTW, colab is available for now.
<a href="https://colab.research.google.com/drive/1-AWeWhPvCTBX0KfMtgtMk10uPU05ihoA?usp=sharing" style="padding-left: 0.5rem;"> <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Google Colab" /> </a>
