### ISSUE TITLE
test_step error

### ISSUE THREAD

**Issue by Andyen512** [YuliangXiu/ICON#73]
Hi, I met a problem as follows:
when I make _test_mode: True_ in the yaml file, the error occurs:
```bash
File "/home/111/code/ICON/lib/dataset/Evaluator.py", line 114, in render_normal
    normal_F = self._render_normal(mesh_F, 0)
  File "/home/111/code/ICON/lib/dataset/Evaluator.py", line 65, in _render_normal
    model_mat[:3, :3] = self._normal_render.euler_to_rot_mat(0, rz, 0)
AttributeError: 'NoneType' object has no attribute 'euler_to_rot_mat'
```
because I'm using the headless machine, then I _export PYOPENGL_PLATFORM=egl_, but another error appears:

```bash
File "/home/111/anaconda3/envs/icon/lib/python3.8/site-packages/OpenGL/platform/baseplatform.py", line 350, in getGLUTFontPointer
    raise NotImplementedError( 
NotImplementedError: Platform does not define a GLUT font retrieval function
```
So I'm confused, the code doesn't support headless machine? How can I solve the problem?

**Comment by YuliangXiu** [comment]
I am still preparing the benchmark testing code, so hasn't tested the `test_mode`. But maybe you can uncomment [lines 63-65](https://github.com/YuliangXiu/ICON/blob/master/apps/ICON.py#L63) to see whether it works.

**Comment by Andyen512** [comment]
but when I uncomment [lines 63-65](https://github.com/YuliangXiu/ICON/blob/master/apps/ICON.py#L63), it still has an error. 
```
freeglut (foo): failed to open display ''
```

So in the training stage, the optim_body() and optim_cloth() function don't work, It's a refinement course after training the netG   right?

**Comment by YuliangXiu** [comment]
Yes, these two functions are used during inference. BTW, I updated the [evaluation code](https://github.com/YuliangXiu/ICON/blob/master/docs/evaluation.md), some bugs for PaMIR, but both ICON and PIFu could work for now. As for the `freeglut` error, there are many relevant blogs to fix it, my solution is `export DISPLAY=:1` but this may not apply for others.

**Comment by VisionaryMind** [comment]
@YuliangXiu, the `freeglut` error is also present in your Google Colab notebook.
