### ISSUE TITLE
The preprocessed normals are reversed.

### ISSUE THREAD

**Issue by EadCat** [YuliangXiu/ICON#77]
Thank you for your work and releasing the source code.

I love this work and am reproducing the source code for future work.
But, I'm not sure why you intended to flip the normal map images as follows.

front normal:
![001](https://user-images.githubusercontent.com/59416168/174265064-538cf01c-3704-474c-a6d7-8225fab16259.png)

and back normal:
![000](https://user-images.githubusercontent.com/59416168/174265102-e9b3137c-5d6e-4692-9137-cb3d3974bad4.png)

Therefore, I modified the code like this:
front normal:
![0525-000](https://user-images.githubusercontent.com/59416168/174265499-d71c823e-508f-470e-92fd-5dc57adbfc2b.png)

back normal:
![0525-000](https://user-images.githubusercontent.com/59416168/174265526-b446829d-da44-4922-9a55-182886b010e1.png)

If you intended to get geometrical information in the occluded areas using PyMAF and Normal network, wouldn't it be better to have no flipping, including arm orientation?
Or does not the direction matter in this work?

Thank you.

**Comment by YuliangXiu** [comment]
This normal map rendering setting is directly inherited from PIFuHD, which will be used for implicit reconstruction. Thus, the normal defined on the **model space** seems more intuitive than yours defined on the **camera space**.

**Comment by EadCat** [comment]
Thank you for the reply.

According to [this issue](https://github.com/facebookresearch/pifuhd/issues/98#issuecomment-744050313), I think the rendered normals are in camera space. Is this understanding correct?

Actually, I'm not sure because I didn't run the PIFuHD's pre-processing code yet.

Additionally, could you provide me with the inherited code? Can I refer to [this one](https://github.com/facebookresearch/pifuhd/blob/main/apps/render_turntable.py)?

**Comment by YuliangXiu** [comment]
The normal rendering code itself is implemented by myself, but I take the insight from PIFuHD

![image](https://user-images.githubusercontent.com/7944350/174424738-a6c357c6-1ba9-4773-b189-6985c8f0352c.png)

**Comment by EadCat** [comment]
front/back side normals from the submodule: model space
rendered normals from the MLP's output: camera space

I understand. Thank you !!
