### ISSUE TITLE
There seems to be a typo in the code？

### ISSUE THREAD

**Issue by sunjc0306** [YuliangXiu/ICON#79]
[link](https://github.com/YuliangXiu/ICON/edit/master/lib/dataset/mesh_util.py)
Is there a typo in this source file.
 ”v0, v1, v2 = vertices[:, 0], vertices[:, 0], vertices[:, 0]“
should probably be changed to
    ”v0, v1, v2 = vertices[:, 0], vertices[:, 1], vertices[:, 2]“

**Comment by YuliangXiu** [comment]
Many thanks for your point out. Just fixed it.
