### ISSUE TITLE
Error: undefined symbol: _ZNSt15__exception_ptr13exception_ptr10_M_releaseEv

### ISSUE THREAD

**Issue by ftaker887** [YuliangXiu/ICON#8]
Getting this error when installing locally on my workstation via colab bash script.

`.../ICON/pytorch3d/pytorch3d/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNSt15__exception_ptr13exception_ptr10_M_releaseEv
`

This after installing pytorch3d locally as recommended. Conda has too many conflicts and never resolves.

Installing torch through pip works (1.8.2+cu111) up until the next steps of infer.py because bvh_distance_queries only supports cuda 11.0. This would most likely require compiling against 11.0, but it will probably lead to more errors as I don't know what this repository's dependencies require as far as torch goes.

**Comment by YuliangXiu** [comment]
colab.sh is designed for online colab, don't use it for your workstation. As for local installation, please refer to [installation](https://github.com/YuliangXiu/ICON/blob/master/docs/Installation.md), step by step.

**Comment by ftaker887** [comment]
> 

Your installation documentation were the first I followed before trying the collab.sh.
Here are the steps I took after cloning the repository and creating a conda environment, prior to the install:

1. `conda install pip`

2. `pip3 install torch==1.8.2+cu111 torchvision==0.9.2+cu111 torchaudio===0.8.2 -f https://download.pytorch.org/whl/lts/1.8/torch_lts.html`

3. `conda install -c conda-forge pyembree`

4. `pip install -r requirements.txt --user`

5. `git clone https://github.com/facebookresearch/pytorch3d.git cd pytorch3d && pip install -e .`

6. Run one of the example scripts.

It works up until it needs to do the 3D pass (bvh) because that version of pytorch is built on cuda 11.1. On step 2, If I use conda to install pytorch, I get the error:

`Error: undefined symbol: _ZNSt15__exception_ptr13exception_ptr10_M_releaseEv`

It's most likely caused from the difference in C versions of which `conda pytorch` and `pip install pytorch` were built with.

**Comment by YuliangXiu** [comment]
1. Please refer to #7 to softlink cuda 11.0, and then install pytorch, pytorch3d, and bvh-distance-queries.
2. I always use conda for pytorch installation, never use pip to install it
3. `undefined symbol: _ZNSt15__exception_ptr13exception_ptr10_M_releaseEv` such error often means you need to re-compile / re-install the relevant package
4. I update a lighter requirements.txt, and delete my unnecessary files, thus you can have another try

**Comment by YuliangXiu** [comment]
@ftaker887 If you finally successfully set up ICON in your workstation, please share your experience here, which may be helpful for other users. Also let me know, then I will close this issue. Thanks

**Comment by ftaker887** [comment]
> 

Hello. I've followed the steps for installing things via conda, and it's still the same issues. 

Installing Pytorch-LTS through PIP, pytorch3d local clone, and bvh-distance-queries doesn't lead to the same compilation errors. 

I haven't tried soft linking CUDA yet, and will try this later when I'm able to.

**Comment by ftaker887** [comment]
Tried all recommended ways of install and no success. The only way this can work in this specific circumstance is upgrading all dependencies to be compatible with with cuda 11.1, and being compatible with conda pytorch3d without locally building.

Soft linking cuda would require installing too many dependencies on my workstation, and would break compatibility with some of the other projects I'm working on.

Unsolved, but closed and moving on as the solution requires too much grunt work.

**Comment by YuliangXiu** [comment]
@ftaker887 I have replaced the `bvh-distance-queries` with `PyTorch3D+Kaolin`, thus you don't need to install it anymore,

**Comment by ftaker887** [comment]
> @ftaker887 I have replaced the `bvh-distance-queries` with `PyTorch3D+Kaolin`, thus you don't need to install it anymore. Also, the CUDA version is not limited to 11.0.
> 
> I just updated the installation scripts, colab can work well for now.
> 
> [ ![Google Colab](https://camo.githubusercontent.com/84f0493939e0c4de4e6dbe113251b4bfb5353e57134ffd9fcab6b8714514d4d1/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667) ](https://colab.research.google.com/drive/1-AWeWhPvCTBX0KfMtgtMk10uPU05ihoA?usp=sharing)

Sorry for the late reply. Thanks for the updates, cheers!
