### ISSUE TITLE
SMPLX in infer.py?

### ISSUE THREAD

**Issue by guayabas** [YuliangXiu/ICON#9]
When using the infer.py sample script is it possible to control the 3D body model being used/generated? I am interested to see if one can get/use the SMPLX in your infer.py pipeline or is it just SMPL supported?

I see in the [installation instructions](https://github.com/YuliangXiu/ICON/blob/master/docs/Installation.md) one can download the SMPLX model but it is mentioned (optional, training used), so makes me wonder the purpose of having the SMPLX in the structure of the data folder.

Thanks and again awesome work.

**Comment by YuliangXiu** [comment]
Quick answer, YES.

For now, ICON only supports two off-the-shelf HPS (Human Pose and Shape Estimator), i.e., [PyMAF and PARE](https://github.com/YuliangXiu/ICON/blob/master/lib/dataset/TestDataset.py#L72), both use SMPL. But it is compatible with other HPS using any mesh-based statistical human model, like SMPL-X.

It is in my TODO list to add [PIXIE](https://pixie.is.tue.mpg.de/) as the third HPS, will let you know when it's ready. If you want other HPS, **pull request** is welcome!

During training, I used SMPL-X ground truth fits from [AGORA](https://agora.is.tue.mpg.de/index.html), so I include SMPL-X in the installation script.

**Comment by YuliangXiu** [comment]
@guayabas Now ICON supports PIXIE (SMPL-X), please check [here](https://github.com/YuliangXiu/ICON/blob/master/apps/infer.py#L89).

```bash
cd ICON/apps

# ICON w/ global filter (better visual details --> lower Normal Error))
python infer.py -cfg ../configs/icon-filter.yaml -gpu 0 -in_dir ../examples -out_dir ../results -hps_type {pixie/pymaf/pare}

# ICON w/o global filter (higher evaluation scores --> lower P2S/Chamfer Error))
python infer.py -cfg ../configs/icon-nofilter.yaml -gpu 0 -in_dir ../examples -out_dir ../results -hps_type {pixie/pymaf/pare}
```
