### ISSUE TITLE
using my own image gets very noisy 3D model

### ISSUE THREAD

**Issue by Holmes-Alan** [YuliangXiu/ICON#91]
Hello, thanks for you sharing the codes. My question is that when I used my own image, the generated 3D mesh was very noisy (not very smooth) even when I already used a global filter to process. Can you tell me what is the problem?

**Comment by YuliangXiu** [comment]
Yes, this is still a limitation of ICON, sometimes produces noisy artifacts. I am working on this issue and will let you know when I have a better model.

Also, increasing the `loop_cloth` a bit will alleviate this issue, which optimizes the geometry according to the predicted clothing normal maps, but this is just a temporary workaround.

**Comment by Holmes-Alan** [comment]
Thanks for quick response!

**Comment by YuliangXiu** [comment]
@Holmes-Alan New cloth-refinement module is released. Use `-loop_cloth 200` to refine ICON's reconstruction, making it as good as the predicted clothing normal image.
![overlap](https://user-images.githubusercontent.com/7944350/181116211-2ed4ab54-73b1-487d-9496-15019dfdbc63.gif)
