### ISSUE TITLE
Inconsistent

### ISSUE THREAD

**Issue by caiyongqi** [YuliangXiu/ICON#92]
Hi, how can I solve the package conflict problem below.
kaolin 0.11.0 requires scipy<=1.5.2,>=1.2.0, but you have scipy 1.7.3 which is incompatible.
rembg 2.0.3 requires scipy==1.7.3, but you have scipy 1.5.2 which is incompatible.

**Comment by YuliangXiu** [comment]
This conflict won't affect the Google Colab installation. If you set up on your own machine, maybe you need to edit the `requirement.txt` of **rembg** to get rid of this conflict warning.
