### ISSUE TITLE
The code seems incorrect for the scale of THU model

### ISSUE THREAD

**Issue by Jarvisss** [YuliangXiu/ICON#95]
https://github.com/YuliangXiu/ICON/blob/9866670053469c8c8b47e92a1d1751dd29a340ab/scripts/render_single.py#L79

maybe a () is missing
scan_scale = 0.6/ ( vertices.max(0)[up_axis] - vertices.min(0)[up_axis] )

**Comment by YuliangXiu** [comment]
Really thanks for pointing out, I just fixed this bug.
