### ISSUE TITLE
Check failed: error == cudaSuccess (209 vs. 0)  

### ISSUE THREAD

**Issue by cedro3** [YuliangXiu/ICON#96]
When I run Google colab, # run the test on examples causes 'Check failed: error == cudaSuccess (209 vs. 0) no kernel image is available for execution on the device'.
What should I do?

--- error massage ---
........
Body Fitting --- normal: 0.121 | silhouette: 0.064 | Total: 0.185:  98% 98/100 [00:25<00:00,  4.09it/s]
Body Fitting --- normal: 0.121 | silhouette: 0.064 | Total: 0.185:  99% 99/100 [00:25<00:00,  4.11it/s]
Body Fitting --- normal: 0.121 | silhouette: 0.064 | Total: 0.185:  99% 99/100 [00:25<00:00,  4.11it/s]
Body Fitting --- normal: 0.121 | silhouette: 0.064 | Total: 0.185: 100% 100/100 [00:25<00:00,  3.89it/s]
[F unbatched_triangle_distance_cuda.cu:441] Check failed: error == cudaSuccess (209 vs. 0)  no kernel image is available for execution on the device

**Comment by JakeFromStateCS** [comment]
I've tracked it down to this line in ICON.py:
```
        sdf = self.reconEngine(
            opt=self.cfg, netG=self.netG, features=features, proj_matrix=None
        )
```

**Comment by YuliangXiu** [comment]
<a href="https://huggingface.co/spaces/Yuliang/ICON"  style='padding-left: 0.5rem;'><img src='https://img.shields.io/badge/%F0%9F%A4%97%20Hugging%20Face-Spaces-orange'></a> <a href='https://colab.research.google.com/drive/1-AWeWhPvCTBX0KfMtgtMk10uPU05ihoA?usp=sharing' style='padding-left: 0.5rem;'><img src='https://colab.research.google.com/assets/colab-badge.svg' alt='Google Colab'></a>

I updated the Google Colab a few days before for a faster environment setup (from 30min to 10min), you can check out the new one.

Also, I also created a HuggingFace Space for users, you can directly test your images without waiting for a long time for environment setup. (The HF space is not very stable, if there is an ERROR, just try it again)
