### ISSUE TITLE
Question about Renderpeople dataset

### ISSUE THREAD

**Issue by krishnaw10** [YuliangXiu/ICON#97]
Hi, 

Congratulations on this great work! 

I had a question about the Renderpeople scans used to train ICON. The Renderpeople datasets comprises 3D posed people, 3D rigged people and 3D animated people. Which of these did you use for training? 

Also regarding the pretrained model provided by you in this repository, it is trained on Renderpeople, right? 

Thank you.

**Comment by YuliangXiu** [comment]
We bought several commercial datasets, like RenderPeople (posed people), 3DPeople, AXYZ, and Humanalloy. The released model is trained on all these datasets.

**Comment by krishnaw10** [comment]
I checked Renderpeople's website. The website has 3 types of datasets: (1)  3D posed people (2) 3D rigged people (3) 3D animated people. Which of the 3 datasets did you use for training ICON?

**Comment by YuliangXiu** [comment]
> I checked Renderpeople's website. The website has 3 types of datasets: (1)  3D posed people (2) 3D rigged people (3) 3D animated people. Which of the 3 datasets did you use for training ICON?

Please check my last reply.

**Comment by krishnaw10** [comment]
Sorry my bad... Understood... Thank you for answering
